/*
 * This file runs in a Node context (it's NOT transpiled by Babel), so use only
 * the ES6 features that are supported by your Node version. https://node.green/
 */

// Configuration for your app
// https://v2.quasar.dev/quasar-cli-webpack/quasar-config-js

const { configure } = require('quasar/wrappers'),
  envparser = require('./src/config/envparser.js'),
  SitemapPlugin = require('sitemap-webpack-plugin').default,
  CopyWebpackPlugin = require('copy-webpack-plugin')

const paths = [
  { path: '/#/' },
  { path: '/#/my-account' },
  { path: '/#/blogs' },
  { path: '/#/blogs/my-bakery-classement-des-meilleurs-boulangerie-de-france' },
  { path: '/#/blogs/comment-definir-une-bonne-boulangerie-sur-my-bakery' },
  { path: '/#/bakerys' },
  { path: "/#/bakery/boulangerie-paris-co-convention" },
  { path: "/#/bakery/boulangerie-paris-co-gat" },
  { path: "/#/bakery/boulangerie-restaurant-sandwicherie-sarg-les-le-mans-le-fournil-de-la-pointe" },
  { path: "/#/bakery/boulangerie-ptisserie-artisanale-aquitaine" },
  { path: "/#/bakery/boulangerie-paris-co-ecoles" },
  { path: "/#/bakery/maison-legui" },
  { path: "/#/bakery/boulangerie-parisienne-berns" },
  { path: "/#/bakery/b2-boulogne-billancourt-boulangerie-au-carr" },
  { path: "/#/bakery/henain-aux-saveurs-du-fournil" },
  { path: "/#/bakery/les-dlices-de-boulogne" },
  { path: "/#/bakery/antone-artisan-boulanger" },
  { path: "/#/bakery/chez-le-boulanger-laurent-lachenal--bordeaux-nansouty" },
  { path: "/#/bakery/dun-passage-lautre-bio-paul-bert" },
  { path: "/#/bakery/eugenie-boulangerie-patisserie--joffre-nantes" },
  { path: "/#/bakery/latelier-banette-montpellier-boulangerie-ptisserie-restauration-rapide" },
  { path: "/#/bakery/boulangerie-ptisserie-maison-coupel" },
  { path: "/#/bakery/boulangerie-du-landrel" },
  { path: "/#/bakery/daveloza" },
  { path: "/#/bakery/le-fournil-de-prosper" },
  { path: "/#/bakery/boulangerie-saint-maurice" },
  { path: "/#/bakery/la-ptisserie-de-la-gare" },
  { path: "/#/bakery/au-refuge-des-saveurs" },
  { path: "/#/bakery/boulangerie-patisserie-carrementpain" },
  { path: "/#/bakery/boulangerie-ptisserie--la-bretagne" },
  { path: "/#/bakery/boulangerie-artisan-banette-centre-commercial-la-coupole" },
  { path: "/#/bakery/boulangerie-lion" },
  { path: "/#/bakery/boulangerie-borea-nantes" },
  { path: "/#/bakery/boulangerie-ptisserie-akharouid-pre-et-fils" },
  { path: "/#/bakery/maison-louot" },
  { path: "/#/bakery/boulangerie-la-madeline" },
  { path: "/#/bakery/boulangerie-au-four-bois" },
  { path: "/#/bakery/le-b-boulangerie-100-bio-dijon" },
  { path: "/#/bakery/boulangerie-artisanale-jf" },
  { path: "/#/bakery/du-pain-pour-demain" },
  { path: "/#/bakery/boulangerie-de-la-porte-guillaume" },
  { path: "/#/bakery/boulangerie-ravau" },
  { path: "/#/bakery/boulangerie-grand-faubourg" },
  { path: "/#/bakery/boulangerie-patisserie--20130" },
  { path: "/#/bakery/la-gourmande" },
  { path: "/#/bakery/boulangerie-mathieu" },
  { path: "/#/bakery/fort-de-feyzin" },
  { path: "/#/bakery/boulangerie-fort" },
  { path: "/#/bakery/maxime-ollivier" },
  { path: "/#/bakery/the-grignette" },
  { path: "/#/bakery/au-quai-des-gourmandises" },
  { path: "/#/bakery/le-chant-de-la-fourne" },
  { path: "/#/bakery/la-croisee-des-pains" },
  { path: "/#/bakery/boulangerie-montmayeur--la-plagne-centre" },
  { path: "/#/bakery/grain-de-dlice--boulangerie-saint-malo" },
  { path: "/#/bakery/boulangerie-larbre-pains" },
  { path: "/#/bakery/dtour-gourmand" },
  { path: "/#/bakery/aux-dlices-de-rochebonne" },
  { path: "/#/bakery/boulangerie-de-tossiat" },
  { path: "/#/bakery/au-bon-fournil" },
  { path: "/#/bakery/boulangerie-pierre-et-marie" },
  { path: "/#/bakery/boulangerie-romy" },
  { path: "/#/bakery/boulangerie-au-creux" },
  { path: "/#/bakery/au-pain-de-vie" },
  { path: "/#/bakery/boulangerie-maison-peronne" },
  { path: "/#/bakery/maison-yvonne--proche-gare-rouen" },
  { path: "/#/bakery/boulangerie-florentin-ptisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-eric-et-sandrine" },
  { path: "/#/bakery/boulangerie-tony-letournel-rouen" },
  { path: "/#/bakery/lpi-de-lautize--boulangerie-peronnet" },
  { path: "/#/bakery/mairie-de-vaux-en-bugey" },
  { path: "/#/bakery/michallon-guillaume" },
  { path: "/#/bakery/peronnet-olivier" },
  { path: "/#/bakery/peronnet" },
  { path: "/#/bakery/boulangerie-bonon" },
  { path: "/#/bakery/le-fournil-de-la-croix-de-pierre" },
  { path: "/#/bakery/boulangerie-boni" },
  { path: "/#/bakery/fournil-rsistance" },
  { path: "/#/bakery/au-temps-passe" },
  { path: "/#/bakery/boulangerie-giraud-banette" },
  { path: "/#/bakery/benoit-claudine-et-franois" },
  { path: "/#/bakery/boulangerie-marchand" },
  { path: "/#/bakery/ainvision-centre-ophtalmologique-pont-dain" },
  { path: "/#/bakery/latelier-du-fromage-les-caves-de-pont-dain" },
  { path: "/#/bakery/boulangerie-marchand-pre-et-fils" },
  { path: "/#/bakery/mairie-de-pont-dain" },
  { path: "/#/bakery/boulanger--ptissier--chocolatier--glacier--christine-et-christophe-marchand" },
  { path: "/#/bakery/les-dames-moustache-laroin" },
  { path: "/#/bakery/le-fournil-du-revermont" },
  { path: "/#/bakery/boulangerie-manu" },
  { path: "/#/bakery/la-fontaine-des-dlices" },
  { path: "/#/bakery/le-fournil-du-rocher-fdr" },
  { path: "/#/bakery/latelier-du-pain" },
  { path: "/#/bakery/auchan-drive-mont-saint-martin" },
  { path: "/#/bakery/aparthotel-adagio-genve-saint-genis-pouilly" },
  { path: "/#/bakery/atout-faire-conciergerie-multi-services" },
  { path: "/#/bakery/au-fournil-utingeois" },
  { path: "/#/bakery/colletta-franois" },
  { path: "/#/bakery/le-petit-salon" },
  { path: "/#/bakery/boulangerie-ptisserie-zanardi" },
  { path: "/#/bakery/martinet-eric" },
  { path: "/#/bakery/mairie-de-saint-didier-sur-chalaronne" },
  { path: "/#/bakery/le-pain-de-chazey" },
  { path: "/#/bakery/boulangerie-fourrier" },
  { path: "/#/bakery/controle-technique-saint-didier-sur-chalaronne-autosecuritas" },
  { path: "/#/bakery/navetat-daniel" },
  { path: "/#/bakery/maison-janvier" },
  { path: "/#/bakery/saint-didier-sur-chalaronne" },
  { path: "/#/bakery/secrets-de-pains" },
  { path: "/#/bakery/le-pain-dannette" },
  { path: "/#/bakery/communaut-de-communes-montrevel-en-bresse" },
  { path: "/#/bakery/market-montrevel-en-bresse" },
  { path: "/#/bakery/poncin-quentin" },
  { path: "/#/bakery/otraditions-gourmandes-ansoud" },
  { path: "/#/bakery/boulangerie-vieux-cressely" },
  { path: "/#/bakery/paintball-panda" },
  { path: "/#/bakery/ptisserie-boulangerie-de-la-commanderie" },
  { path: "/#/bakery/boulangerie-naturea-saint-andre-de-corcy" },
  { path: "/#/bakery/karting-montrevel-en-bresse" },
  { path: "/#/bakery/boulangerie-cedric-et-maryline" },
  { path: "/#/bakery/boulangerie-triboulet" },
  { path: "/#/bakery/la-manufacture-des-pains--chaleins" },
  { path: "/#/bakery/intermarch-super-neuville-sur-ain" },
  { path: "/#/bakery/boulangerie-ptisserie-deneuve" },
  { path: "/#/bakery/legrand-christian-bernard" },
  { path: "/#/bakery/patisserie-delume" },
  { path: "/#/bakery/boulangerie-la-mie-daubance" },
  { path: "/#/bakery/boulangerie-patisserie-thil" },
  { path: "/#/bakery/boulangerie-ptisserie-tillet" },
  { path: "/#/bakery/le-petit-commerce" },
  { path: "/#/bakery/boulangerie-comtet" },
  { path: "/#/bakery/maison-karl" },
  { path: "/#/bakery/hpital-priv-saint-martin--ramsay-sant" },
  { path: "/#/bakery/boulangerie-du-thil" },
  { path: "/#/bakery/pain-snacking-baland-auch" },
  { path: "/#/bakery/boulangerie-du-vieux-chteau" },
  { path: "/#/bakery/le-fournil-de-chtenay" },
  { path: "/#/bakery/collge-saint-martin-de-france" },
  { path: "/#/bakery/boulangerie-slandbrot" },
  { path: "/#/bakery/la-symphonie-des-saveurs-beauzacoises" },
  { path: "/#/bakery/boulangerie-ptisserie-cheyenne-et-paul" },
  { path: "/#/bakery/la-fourne-bressane" },
  { path: "/#/bakery/boulangerie-de-saint-michel" },
  { path: "/#/bakery/boulangerie-bozalino" },
  { path: "/#/bakery/pichat-fabien" },
  { path: "/#/bakery/ecole-christian-vabret--boulangerie--ptisserie--cuisine" },
  { path: "/#/bakery/les-soeurettes" },
  { path: "/#/bakery/opticien-chatillon-en-michaille--optical-center" },
  { path: "/#/bakery/boulangerie-fromagerie-savey" },
  { path: "/#/bakery/boulangerie-sainte-fauste--paul-ginisty" },
  { path: "/#/bakery/la-miette-dadripain" },
  { path: "/#/bakery/boulangerie-besnier-le-fournil-de-la-pimotire" },
  { path: "/#/bakery/au-caprice" },
  { path: "/#/bakery/golf-htel-de-mont-griffon-restaurant-des-lacs" },
  { path: "/#/bakery/boulangerie-patisserie-philippe-trin" },
  { path: "/#/bakery/o-to-bom--boulangerie-de-croix-paquet" },
  { path: "/#/bakery/dsert-jean-jacques-rousseau" },
  { path: "/#/bakery/marie-chambel" },
  { path: "/#/bakery/la-route-des-pains" },
  { path: "/#/bakery/intermarch-super-saint-dizier" },
  { path: "/#/bakery/le-fournil-de-beutre" },
  { path: "/#/bakery/boulangerie-la-croise" },
  { path: "/#/bakery/boulangerie-ptisserie-samuel-mathieu" },
  { path: "/#/bakery/boulangerie--ptisserie-co-marie" },
  { path: "/#/bakery/boulanger-bordeaux--mrignac" },
  { path: "/#/bakery/boulangerie-galzin" },
  { path: "/#/bakery/boulangerie-ptisserie-de-carlepont" },
  { path: "/#/bakery/le-moulin-saint-benoit" },
  { path: "/#/bakery/le-champ-du-pain" },
  { path: "/#/bakery/au-levain-du-morin" },
  { path: "/#/bakery/la-baguette-bndictine" },
  { path: "/#/bakery/la-fleur-du-pain" },
  { path: "/#/bakery/la-mazarine" },
  { path: "/#/bakery/le-fournil-de-qwartz-douceurs-pains" },
  { path: "/#/bakery/aux-dlices-de-douvres" },
  { path: "/#/bakery/boulangerie-ptisserie-rouzeau" },
  { path: "/#/bakery/sas-girard--villars-les-dombes" },
  { path: "/#/bakery/cline-et-franois" },
  { path: "/#/bakery/ptissier-chocolatier-boulanger-maison-dumontet-la-chapelle" },
  { path: "/#/bakery/mcdonalds" },
  { path: "/#/bakery/combier-frdric" },
  { path: "/#/bakery/boulangerie-patisserie-artisanale-la-petite-fringale-dalice" },
  { path: "/#/bakery/boulangerie-de-l-eglise-saint-justin" },
  { path: "/#/bakery/boulangerie-patisserie-kling" },
  { path: "/#/bakery/boulangerie-gendre" },
  { path: "/#/bakery/boulangerie-st-just" },
  { path: "/#/bakery/lami-du-pain-sarl-le-pain-de-vie" },
  { path: "/#/bakery/boulangerie-patisserie-ad-dusanter" },
  { path: "/#/bakery/boulangerie-ptisserie-augusta--civrieux" },
  { path: "/#/bakery/boulangerie-aubut" },
  { path: "/#/bakery/boulangerie-tentations-saveurs" },
  { path: "/#/bakery/boulangerie-saint-benot" },
  { path: "/#/bakery/le-brasille" },
  { path: "/#/bakery/piscines-en-bugey" },
  { path: "/#/bakery/boulangerie-baudement-denis" },
  { path: "/#/bakery/autant-de-pains" },
  { path: "/#/bakery/du-moulin-au-ptrin" },
  { path: "/#/bakery/ccile-et-fabrice-hritier" },
  { path: "/#/bakery/latelier-du-dlice" },
  { path: "/#/bakery/jasmin-aurlien" },
  { path: "/#/bakery/teillard-albert" },
  { path: "/#/bakery/chez-mademoiselle--restaurant-divonne-les-bains" },
  { path: "/#/bakery/kocksch-pierre" },
  { path: "/#/bakery/boulangerie-ptisserie-lm-gouzy" },
  { path: "/#/bakery/les-dlices-davray" },
  { path: "/#/bakery/ecole-saint-joseph-montmerle-sur-sane" },
  { path: "/#/bakery/collge-priv-saint-jean-de-passy" },
  { path: "/#/bakery/crdit-agricole-centre-est-montmerle-sur-saone" },
  { path: "/#/bakery/eveil-saint-andr-dhuiriat" },
  { path: "/#/bakery/le-fournil-saint-andr-chteauroux-skate-park" },
  { path: "/#/bakery/bon-frdric" },
  { path: "/#/bakery/chaudpain-sarl" },
  { path: "/#/bakery/glise-saint-jean-de-montmartre" },
  { path: "/#/bakery/mairie-de-saint-andr-de-bg" },
  { path: "/#/bakery/crozier-anthony" },
  { path: "/#/bakery/patisserie-saint-andr-letendart" },
  { path: "/#/bakery/au-pain-des-lys" },
  { path: "/#/bakery/servignat-franck" },
  { path: "/#/bakery/les-copains-boulangers" },
  { path: "/#/bakery/les-dlices-de-st-andr" },
  { path: "/#/bakery/mairie-de-montmerle-sur-sane" },
  { path: "/#/bakery/ambrieu-en-bugey-air-base" },
  { path: "/#/bakery/boulangerie-patisserie-epicerie-david-carvalho" },
  { path: "/#/bakery/la-boulangerie-du-moulin-rouge" },
  { path: "/#/bakery/boulangerie-journet-antoine" },
  { path: "/#/bakery/prvost-didier" },
  { path: "/#/bakery/bourgeois-christophe" },
  { path: "/#/bakery/chez-bol--le-pain-de-villemotier--le-relais-de-villemotier" },
  { path: "/#/bakery/boulangerie-abrivard" },
  { path: "/#/bakery/boulanger-beynost" },
  { path: "/#/bakery/boulangerie-bourcet-latelier-du-pain" },
  { path: "/#/bakery/boutique-ferme-dorvilliers-paysans-boulangers-bio" },
  { path: "/#/bakery/maison-thevenin" },
  { path: "/#/bakery/deleaz-bruno" },
  { path: "/#/bakery/boulangerie-les-bls-dor" },
  { path: "/#/bakery/le-craquelin" },
  { path: "/#/bakery/la-crousti-pain" },
  { path: "/#/bakery/ribeiro-stephane" },
  { path: "/#/bakery/chevalier-romain" },
  { path: "/#/bakery/boulanger-bourg-en-bresse" },
  { path: "/#/bakery/boulangerie-la-notre" },
  { path: "/#/bakery/aux-delices-de-beny" },
  { path: "/#/bakery/fournil-de-canteloup" },
  { path: "/#/bakery/leroy-herv" },
  { path: "/#/bakery/radiologie-chatillon-sur-chalaronne" },
  { path: "/#/bakery/boulangerie-fages" },
  { path: "/#/bakery/la-mie-de-pain" },
  { path: "/#/bakery/boulangerie-fargues" },
  { path: "/#/bakery/mairie-de-chtillon-sur-chalaronne" },
  { path: "/#/bakery/la-tropzienne" },
  { path: "/#/bakery/boulangerie-farge" },
  { path: "/#/bakery/market-chtillon-sur-chalaronne" },
  { path: "/#/bakery/boulangerie-ptisserie-collongues" },
  { path: "/#/bakery/sarl-la-mie-de-pain" },
  { path: "/#/bakery/le-rendez-vous-des-gourmets" },
  { path: "/#/bakery/lepi-dor" },
  { path: "/#/bakery/la-mie-dor" },
  { path: "/#/bakery/boulangerie-porte-dalsace" },
  { path: "/#/bakery/l-ami-de-pain" },
  { path: "/#/bakery/boulangerie-de-laurore" },
  { path: "/#/bakery/boulangerie-carrillat" },
  { path: "/#/bakery/boulangerie-linstant-gourmand" },
  { path: "/#/bakery/comptoir-des-gourmets" },
  { path: "/#/bakery/boulangerie-oyonnaxienne" },
  { path: "/#/bakery/boulangerie-des-linandes" },
  { path: "/#/bakery/au-ptrin-dantan" },
  { path: "/#/bakery/dumez-sbastien" },
  { path: "/#/bakery/au-paradis-gourmand" },
  { path: "/#/bakery/restaurant-le-vieux-lyon" },
  { path: "/#/bakery/vival" },
  { path: "/#/bakery/boulangerie-dumoulin" },
  { path: "/#/bakery/boulangerie-et-alimentation-maurice-grandjean" },
  { path: "/#/bakery/boulanger-annecy--seynod" },
  { path: "/#/bakery/boulangerie-kennedy" },
  { path: "/#/bakery/simandre-sur-suran" },
  { path: "/#/bakery/boulangerie-sandwicherie-artisanale-ferey" },
  { path: "/#/bakery/boulangerie-st-rmy" },
  { path: "/#/bakery/fromagerie-simandre-sur-suran" },
  { path: "/#/bakery/boulangerie-patisserie-le-pont-paron" },
  { path: "/#/bakery/domaine-saint-jean-le-vieux" },
  { path: "/#/bakery/feuilleuse-laurent" },
  { path: "/#/bakery/carvalho-manuel" },
  { path: "/#/bakery/elodie-arnaud" },
  { path: "/#/bakery/boulangerie-georges" },
  { path: "/#/bakery/boulangerie-georges--boulangerie-au-feu-de-bois-et-ptisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-georges" },
  { path: "/#/bakery/george-patrick" },
  { path: "/#/bakery/boulangerie-ptisserie-cyril-bondon" },
  { path: "/#/bakery/aux-portes-de-largonne-sebastien-jacquemin" },
  { path: "/#/bakery/maison-bettant" },
  { path: "/#/bakery/crtin-mathieu" },
  { path: "/#/bakery/au-four-au-moulin" },
  { path: "/#/bakery/la-manufacture-des-pains--ambrieux-en-dombes" },
  { path: "/#/bakery/lauthentiq" },
  { path: "/#/bakery/aux-dlices-dompierrois-mr-aucaigne-olivier" },
  { path: "/#/bakery/boulangerie-de-versonnex" },
  { path: "/#/bakery/boulangerie-de-montluel" },
  { path: "/#/bakery/le-fournil-de-dommartin" },
  { path: "/#/bakery/latelier-des-pains" },
  { path: "/#/bakery/duret-jrme" },
  { path: "/#/bakery/boulangerie-carlier" },
  { path: "/#/bakery/boulangerie-carlier-crateur-denvies-artisan-fabricant" },
  { path: "/#/bakery/boulangerie-callier" },
  { path: "/#/bakery/boulangerie-camille" },
  { path: "/#/bakery/le-petit-fournil" },
  { path: "/#/bakery/la-chouquette-dore" },
  { path: "/#/bakery/la-pomme-damour" },
  { path: "/#/bakery/marie-blachre-boulangerie-sandwicherie-tarterie" },
  { path: "/#/bakery/boulangerie-chez-jules-beynost" },
  { path: "/#/bakery/latelier-lagnieu" },
  { path: "/#/bakery/foubert-christophe" },
  { path: "/#/bakery/les-dlices-de-simonette" },
  { path: "/#/bakery/boulangerie-du-mail-la" },
  { path: "/#/bakery/boulangerie-velon-jol" },
  { path: "/#/bakery/boulangerie-duvignaud" },
  { path: "/#/bakery/ptisserie-perruche" },
  { path: "/#/bakery/spa-de-dompierre-sur-veyle" },
  { path: "/#/bakery/rapaud-didier" },
  { path: "/#/bakery/boulanger-pau--lons" },
  { path: "/#/bakery/aux-dlices-dambre" },
  { path: "/#/bakery/boulangerie-ptisserie-girondon" },
  { path: "/#/bakery/boulangerie-le-goff" },
  { path: "/#/bakery/latelier-saint-vulbas" },
  { path: "/#/bakery/boulangerie-du-lange" },
  { path: "/#/bakery/boulangerie-ptisserie-baillivy" },
  { path: "/#/bakery/boulangerie--ptisserie-georges-blanc" },
  { path: "/#/bakery/aux-saveurs-denfance" },
  { path: "/#/bakery/maison-chevillard--artisan-boulanger" },
  { path: "/#/bakery/boulangerie-ptisserie-bardoulet" },
  { path: "/#/bakery/boulangerie-porticcio-ptisserie-ettori-salon-de-th" },
  { path: "/#/bakery/boulangerie-porte-brunet" },
  { path: "/#/bakery/boulangerie-ponsard" },
  { path: "/#/bakery/boulangerie-dos-santos" },
  { path: "/#/bakery/au-dlice-des-jumelles" },
  { path: "/#/bakery/boulangerie-prost" },
  { path: "/#/bakery/boulangerie-louis-lamour" },
  { path: "/#/bakery/boulangerie-ptisserie-schneider-pascal" },
  { path: "/#/bakery/farine" },
  { path: "/#/bakery/le-fournil-rustique" },
  { path: "/#/bakery/boulangerie-ptisserie-maison-vie-hauterives" },
  { path: "/#/bakery/fournil-de-lya" },
  { path: "/#/bakery/boulangerie-patisserie-rosa" },
  { path: "/#/bakery/le-fournil-dangel" },
  { path: "/#/bakery/jauzelon-yannis" },
  { path: "/#/bakery/boulangerie-lemaire" },
  { path: "/#/bakery/coutarel-david" },
  { path: "/#/bakery/boulangerie-des-tilleuls" },
  { path: "/#/bakery/au-carrefour-des-delices" },
  { path: "/#/bakery/boulangerie-brion" },
  { path: "/#/bakery/oro-bianco" },
  { path: "/#/bakery/au-bon-vieux-levain" },
  { path: "/#/bakery/au-rendez-vous-des-gourmets" },
  { path: "/#/bakery/la-corbeille-pain" },
  { path: "/#/bakery/boulangerie-la-canne-sucre" },
  { path: "/#/bakery/boulanger-montceau-les-mines" },
  { path: "/#/bakery/boulangerie-banette" },
  { path: "/#/bakery/boulangerie-lentracte" },
  { path: "/#/bakery/jocteur-le-boulanger-de-lentilly" },
  { path: "/#/bakery/le-fournil-de-lent" },
  { path: "/#/bakery/au-coeur-dlice" },
  { path: "/#/bakery/mairie-de-valserhne" },
  { path: "/#/bakery/aroclub-de-bellegarde-vouvray" },
  { path: "/#/bakery/viaduc-de-bellegarde" },
  { path: "/#/bakery/lami-dpain" },
  { path: "/#/bakery/market-saint-denis-les-bourg" },
  { path: "/#/bakery/mairie-de-saint-denis-ls-bourg" },
  { path: "/#/bakery/mairie-de-bohas-meyriat-rignat" },
  { path: "/#/bakery/didier-vieu" },
  { path: "/#/bakery/au-fournil-gourmand" },
  { path: "/#/bakery/pain-patisserie-maison-christe" },
  { path: "/#/bakery/boulangerie--ptisserie-r-joyeux-depuis-1934" },
  { path: "/#/bakery/boulangerie-biscuits-joyeux--dinard" },
  { path: "/#/bakery/latelier-joyeux--boulangerie-caf" },
  { path: "/#/bakery/boulangerie--ptisserie-joyeux--la-madeleine" },
  { path: "/#/bakery/boulangerie-bziat-frres" },
  { path: "/#/bakery/boulangerie-c-romain" },
  { path: "/#/bakery/beziat-frres" },
  { path: "/#/bakery/patisserie-du-lavoir" },
  { path: "/#/bakery/boulangerie-la-tchanque-ws-montauban" },
  { path: "/#/bakery/boulangerie-ptisserie-bordet" },
  { path: "/#/bakery/meuriau-arnaud" },
  { path: "/#/bakery/boulangerie-couturier" },
  { path: "/#/bakery/humbert-sbastien" },
  { path: "/#/bakery/la-panire" },
  { path: "/#/bakery/la-mie-des-saveurs" },
  { path: "/#/bakery/admr-villieu-loyes-mollon" },
  { path: "/#/bakery/le-fournil-de-maelys" },
  { path: "/#/bakery/boulangerie-au-soleil" },
  { path: "/#/bakery/boulangerie-des-gourmets" },
  { path: "/#/bakery/maison-bav" },
  { path: "/#/bakery/boulangerie-les-3-k" },
  { path: "/#/bakery/boulangerie-bio-au-feu-de-bois" },
  { path: "/#/bakery/le-fournil-de-mrande--angi" },
  { path: "/#/bakery/tournelle-fabien" },
  { path: "/#/bakery/boulangerie-le-fournil-du-moulin-patisserie" },
  { path: "/#/bakery/boulangerie-hombecq" },
  { path: "/#/bakery/boulangerie--ptisserie-pierre-laporte" },
  { path: "/#/bakery/o-gourmet-chabault" },
  { path: "/#/bakery/office-de-tourisme-du-pays-de-thirache" },
  { path: "/#/bakery/boulangerie-du-march--pinguet" },
  { path: "/#/bakery/lorette-boulangerie-ptisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-banette-bracco" },
  { path: "/#/bakery/boulangerie-michon-christophe" },
  { path: "/#/bakery/boulangerie-patisserie-la-vivaroise" },
  { path: "/#/bakery/au-bel-accueil" },
  { path: "/#/bakery/mairie-de-chivres-en-laonnois" },
  { path: "/#/bakery/a-la-brioche-feuillete" },
  { path: "/#/bakery/boulangerie-ptisserie-robert" },
  { path: "/#/bakery/la-ptrie-de-beaurieux" },
  { path: "/#/bakery/le-gaa" },
  { path: "/#/bakery/gaya-cuisine-de-bords-de-mer-pierre-gagnaire" },
  { path: "/#/bakery/au-fournil-de-saint-amand" },
  { path: "/#/bakery/boulangerie-breuzard" },
  { path: "/#/bakery/le-petit-petrin" },
  { path: "/#/bakery/boulangerie-ptisserie-eveillard" },
  { path: "/#/bakery/la-gourmandine-boulangerie-pat-sophie" },
  { path: "/#/bakery/le-delicio" },
  { path: "/#/bakery/le-four-de-la-madeleine" },
  { path: "/#/bakery/boulangerie-moulin-neuf-pain-bio-cuit-au-feu-de-bois" },
  { path: "/#/bakery/boulangerie-les-dlices-du-moulin" },
  { path: "/#/bakery/boulangerie-le-moulin-de-paou" },
  { path: "/#/bakery/le-grain-de-bl" },
  { path: "/#/bakery/htel-full-colors" },
  { path: "/#/bakery/boulangerie-ptisserie-naudou" },
  { path: "/#/bakery/boulangerie-la-guernouille" },
  { path: "/#/bakery/boulangerie-baillon" },
  { path: "/#/bakery/le-bouedec-freres" },
  { path: "/#/bakery/bouetard-laurent" },
  { path: "/#/bakery/boulangerie-ptisserie-dlices-de-bouaine" },
  { path: "/#/bakery/boulangerie-de-bou" },
  { path: "/#/bakery/boulangerie-mc-boure" },
  { path: "/#/bakery/la-boulangerie-de-saint-michel" },
  { path: "/#/bakery/boulangerie-st-michel" },
  { path: "/#/bakery/boulangerie-patisserie-st-michel" },
  { path: "/#/bakery/connexion-partenaire-boulanger-castres" },
  { path: "/#/bakery/boulangerie-marfaing-herenger" },
  { path: "/#/bakery/lespace-gourmand" },
  { path: "/#/bakery/aux-dlices-normands" },
  { path: "/#/bakery/le-croqen-bouche-boulangerie-ptisserie-jousserand" },
  { path: "/#/bakery/la-boulange-de-bergson" },
  { path: "/#/bakery/esprit-boulange" },
  { path: "/#/bakery/boulanger-st-etienne-steel" },
  { path: "/#/bakery/terres-et-eaux--amiens" },
  { path: "/#/bakery/le-jardin-des-gourmandises" },
  { path: "/#/bakery/secrets-de-pains-l-atelier-grisolles" },
  { path: "/#/bakery/mairie-de-courcelles-sur-vesle" },
  { path: "/#/bakery/boulangerie-courcelle" },
  { path: "/#/bakery/bakery-zunic--the-wood-burning-oven" },
  { path: "/#/bakery/oise-aisne-american-cemetery" },
  { path: "/#/bakery/tonton-du-bread--boulangerie-ptisserie-caf-restaurant" },
  { path: "/#/bakery/boulangerie-du-layon" },
  { path: "/#/bakery/boulangerie-patisserie-sarl-idenn" },
  { path: "/#/bakery/mairie-de-trlou-sur-marne" },
  { path: "/#/bakery/horbacz-andr" },
  { path: "/#/bakery/boulangerie-bcherand-chtel" },
  { path: "/#/bakery/boulangerie-ptisserie-chocolaterie-bcherand" },
  { path: "/#/bakery/dlices-et-tradition" },
  { path: "/#/bakery/nogent-l-artaud" },
  { path: "/#/bakery/camping-lartaudois" },
  { path: "/#/bakery/jofrin-julien" },
  { path: "/#/bakery/bocquel-juliana-et-laurent" },
  { path: "/#/bakery/le-dlice-de-puiseux" },
  { path: "/#/bakery/le-fournil-des-coteaux" },
  { path: "/#/bakery/perroy-jean-philippe" },
  { path: "/#/bakery/march-campagnard-de-marigny-en-orxois" },
  { path: "/#/bakery/boulangerie-marini--trattoria" },
  { path: "/#/bakery/boulangerie-forestier-philippe" },
  { path: "/#/bakery/boulangerie-de-neuilly-saint-front" },
  { path: "/#/bakery/le-fournil-de-quessy" },
  { path: "/#/bakery/boulangerie-fortin-anciennement-gras-jean-michel" },
  { path: "/#/bakery/favereaux-hubert" },
  { path: "/#/bakery/aux-delices-de-palomy" },
  { path: "/#/bakery/boulangerie-fleury" },
  { path: "/#/bakery/boulangerie-fleurysette" },
  { path: "/#/bakery/la-fourne-des-restriens" },
  { path: "/#/bakery/fleury-laurent" },
  { path: "/#/bakery/artisan-boulangerie-ptisserie-de-fleury" },
  { path: "/#/bakery/le-mitron-rosierois" },
  { path: "/#/bakery/boulangerie-maison-lacroix" },
  { path: "/#/bakery/maison-cleret" },
  { path: "/#/bakery/boulangerie-blanchard" },
  { path: "/#/bakery/boulangerie-de-vendeuil" },
  { path: "/#/bakery/thiebault" },
  { path: "/#/bakery/maison-lenoir" },
  { path: "/#/bakery/aux-dlices-dacy" },
  { path: "/#/bakery/boulangerie-ptisserie-rouxel" },
  { path: "/#/bakery/lamandine" },
  { path: "/#/bakery/les-gourmandises-de-saint-pierre" },
  { path: "/#/bakery/symphonies-boulangerie--ptisserie" },
  { path: "/#/bakery/boulangerie-lpi" },
  { path: "/#/bakery/boulangerie-de-l-europe" },
  { path: "/#/bakery/boulangerie-eric-kayser--bercy-village" },
  { path: "/#/bakery/boulangerie-de-bercy--pizzeria" },
  { path: "/#/bakery/maison-roy" },
  { path: "/#/bakery/connexion-partenaire-boulanger-davezieux" },
  { path: "/#/bakery/les-dlices-de-la-madeleine" },
  { path: "/#/bakery/la-fournee-beaunoise" },
  { path: "/#/bakery/le-pain-dolivier" },
  { path: "/#/bakery/abbaye-de-bellefontaine" },
  { path: "/#/bakery/boulangerie-lou-pan-angeli" },
  { path: "/#/bakery/larbre-a-pains" },
  { path: "/#/bakery/aux-dlices-des-fourches-laval" },
  { path: "/#/bakery/boulangerie-perlimpainpain-saint-romain" },
  { path: "/#/bakery/boulanger-rivesaltes" },
  { path: "/#/bakery/thermes-de-vals-les-bains-spa-squoia-redwood" },
  { path: "/#/bakery/boulangerie-ptisserie-borne" },
  { path: "/#/bakery/boulangerie-genet" },
  { path: "/#/bakery/boulangerie-saint-germain" },
  { path: "/#/bakery/boulangerie-ptisserie-honorino-fonseca-cousinerie" },
  { path: "/#/bakery/boulangerie-ptisserie-honorino-fonseca-ascq" },
  { path: "/#/bakery/boulangerie-ptisserie-christian-larroque-et-ses-fils" },
  { path: "/#/bakery/boulangerie-ptisserie-les-tabliers-toqus-by-sbastien-baye" },
  { path: "/#/bakery/le-fournil-de-lauzon" },
  { path: "/#/bakery/garnara-pascal" },
  { path: "/#/bakery/boulangerie-lebeurrier" },
  { path: "/#/bakery/mairie-de-boulieu-ls-annonay" },
  { path: "/#/bakery/boulangerie-michel" },
  { path: "/#/bakery/au-tour-des-traditions" },
  { path: "/#/bakery/boulangerie-saint-vincent" },
  { path: "/#/bakery/boulangerie-patisserie-de-la-sablire" },
  { path: "/#/bakery/boulangerie-patisserie-sainte-claire" },
  { path: "/#/bakery/mamie" },
  { path: "/#/bakery/aux-dlices-de-saint-clair" },
  { path: "/#/bakery/sarl-privat-et-fils-boulangerie" },
  { path: "/#/bakery/boulangerie-des-mines" },
  { path: "/#/bakery/ganne-freddy" },
  { path: "/#/bakery/boulangerie-brice-et-marie" },
  { path: "/#/bakery/le-fournil-de-malbosc" },
  { path: "/#/bakery/boulangerie-festival-du-pains" },
  { path: "/#/bakery/rabanit-luc" },
  { path: "/#/bakery/le-fournil-d-arthur" },
  { path: "/#/bakery/monange-sbastien" },
  { path: "/#/bakery/mairie-saint-maurice-dibie" },
  { path: "/#/bakery/au-pav-de-saint-rgis" },
  { path: "/#/bakery/boulangerie-ptisserie-breugnot" },
  { path: "/#/bakery/le-moulin-de-saint-jean" },
  { path: "/#/bakery/martial-champagne" },
  { path: "/#/bakery/champs-pains" },
  { path: "/#/bakery/boulangerie-palardy-lpi-du-marais" },
  { path: "/#/bakery/tout-en-douceur" },
  { path: "/#/bakery/sarl-le-fournil-du-tanargue" },
  { path: "/#/bakery/boulangerie-l-olivier" },
  { path: "/#/bakery/bidache" },
  { path: "/#/bakery/baptiste-mattin" },
  { path: "/#/bakery/buso-didier-didier" },
  { path: "/#/bakery/connexion-partenaire-boulanger-ruoms" },
  { path: "/#/bakery/moula-christophe" },
  { path: "/#/bakery/boulangerie-borie" },
  { path: "/#/bakery/boulangerie-ksl" },
  { path: "/#/bakery/les-caprices-demily" },
  { path: "/#/bakery/boulangerie-prunet" },
  { path: "/#/bakery/boulangerie-ptisserie-pollizzi" },
  { path: "/#/bakery/boulangerie-ptisserie-maison-izorche" },
  { path: "/#/bakery/boulangerie-ptisserie-wastine" },
  { path: "/#/bakery/boulangerie-gauthier-david" },
  { path: "/#/bakery/au-coeur-de-notre-dame" },
  { path: "/#/bakery/boulangerie-patisserie-du-boulevard" },
  { path: "/#/bakery/boulangerie-ptisserie-segnerande" },
  { path: "/#/bakery/boulangerie-ptisserie-malleval" },
  { path: "/#/bakery/connexion-partenaire-boulanger-les-vans" },
  { path: "/#/bakery/la-boulangerie-coux" },
  { path: "/#/bakery/le-fournil-gourmand" },
  { path: "/#/bakery/casino--saint-didier-sous-aubenas" },
  { path: "/#/bakery/decathlon-essentiel-saint-didier-sous-aubenas" },
  { path: "/#/bakery/la-sarrasine" },
  { path: "/#/bakery/le-fournil-sarrassois" },
  { path: "/#/bakery/boulangerie-gavroche" },
  { path: "/#/bakery/furstoss" },
  { path: "/#/bakery/le-fournil-de-la-tradition" },
  { path: "/#/bakery/vion-olivier" },
  { path: "/#/bakery/camping-municipal-de-st-martin-dardche" },
  { path: "/#/bakery/boulangerie-ptisserie-rissoan-brice-et-laetitia" },
  { path: "/#/bakery/boulangerie-de-labeaume" },
  { path: "/#/bakery/boulangerie-mercier-tisserand" },
  { path: "/#/bakery/boulangerie-mercier" },
  { path: "/#/bakery/mairie-de-bourg-saint-andol" },
  { path: "/#/bakery/la-ronde-des-pains" },
  { path: "/#/bakery/au-ptit-creux-du-pilat" },
  { path: "/#/bakery/salle-des-sapins-saint-romain-de-lerps" },
  { path: "/#/bakery/les-epicurieux" },
  { path: "/#/bakery/au-gout-du-jour" },
  { path: "/#/bakery/guapita-institut" },
  { path: "/#/bakery/lepi-cerie" },
  { path: "/#/bakery/poivre-serge" },
  { path: "/#/bakery/centre-de-vacances-et-de-loisirs-saint-andr-en-vivarais" },
  { path: "/#/bakery/boulangerie-du-mesnil" },
  { path: "/#/bakery/la-gourdanaise" },
  { path: "/#/bakery/boulangerie-le-fournil-de-mathieu" },
  { path: "/#/bakery/boulangerie-saint-cyr" },
  { path: "/#/bakery/les-gourmets-de-saint-cyr" },
  { path: "/#/bakery/boulangerie-rendez-vous-gourmand" },
  { path: "/#/bakery/sarl-boulangerie-palisse" },
  { path: "/#/bakery/boulangerie-patisserie-rivat" },
  { path: "/#/bakery/latelier-du-pain-boulangerie-ptisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-gagnaire-et-fils" },
  { path: "/#/bakery/boulangerie-le-cheylard-andr-laurent" },
  { path: "/#/bakery/au-fournil-de-clem" },
  { path: "/#/bakery/boulangerie-ptisserie-le-rocher" },
  { path: "/#/bakery/au-palais-des-pains" },
  { path: "/#/bakery/la-gustive-l-f-rochereau" },
  { path: "/#/bakery/saint-michel-de-picpus--collge-lyce-cpge" },
  { path: "/#/bakery/boulangerie-pajol" },
  { path: "/#/bakery/boulangerie-ardoix" },
  { path: "/#/bakery/albon-pain" },
  { path: "/#/bakery/au-pierrot-dantan--boulangerie" },
  { path: "/#/bakery/razon-frres-sarl" },
  { path: "/#/bakery/le-kiosque-pizzas-la-voulte-sur-rhne" },
  { path: "/#/bakery/mairie-de-la-voulte-sur-rhne" },
  { path: "/#/bakery/intermarch-super-la-voulte-sur-rhone" },
  { path: "/#/bakery/la-belle-farinire" },
  { path: "/#/bakery/boulangerie-lopez" },
  { path: "/#/bakery/eaux-paradis" },
  { path: "/#/bakery/cotte-et-fils" },
  { path: "/#/bakery/boulangerie-saint-sylvestre-sur-lot" },
  { path: "/#/bakery/boulangerie-ptisserie-maison-guilhem-st-sylvestrelot" },
  { path: "/#/bakery/la-mie-ardchoise" },
  { path: "/#/bakery/boulangerie-marsaudon-stphane" },
  { path: "/#/bakery/boulangerie-marsan" },
  { path: "/#/bakery/charmes-sur-rhne" },
  { path: "/#/bakery/mairie-de-charmes-sur-rhne" },
  { path: "/#/bakery/ml-maison-laudet" },
  { path: "/#/bakery/boulangerie-ptisserie--martial-piazza" },
  { path: "/#/bakery/le-fournil-de-lolivier" },
  { path: "/#/bakery/boulanger-aubenas" },
  { path: "/#/bakery/boulangerie-du-beffroi-aubignan" },
  { path: "/#/bakery/chez-franoise-st-laurent-les-bains" },
  { path: "/#/bakery/thermes-de-saint-laurent-les-bains" },
  { path: "/#/bakery/boulangerie-terre-de-beaulieu" },
  { path: "/#/bakery/le-fournil-de-beaulieu--14000" },
  { path: "/#/bakery/beaulieu" },
  { path: "/#/bakery/boulangerie-ptisserie-les-petits-clos" },
  { path: "/#/bakery/au-cdre" },
  { path: "/#/bakery/boulangerie-ptisserie-andr" },
  { path: "/#/bakery/boulangerie-ptisserie-karine-et-laurent-valley" },
  { path: "/#/bakery/maison-scherer" },
  { path: "/#/bakery/bakery-edith-lor" },
  { path: "/#/bakery/boulangerie-lorang" },
  { path: "/#/bakery/boulangerie-lorrain-tradition" },
  { path: "/#/bakery/boulangerie-lorrier" },
  { path: "/#/bakery/maison-tanay" },
  { path: "/#/bakery/fred--artisan-boulanger--vincennes" },
  { path: "/#/bakery/boulangerie-avenue-de-paris" },
  { path: "/#/bakery/la-fourne-lanonnaise" },
  { path: "/#/bakery/boulangerie-ptisserie-bellanger" },
  { path: "/#/bakery/boulangerie-du-bourg" },
  { path: "/#/bakery/maison-haudrechy" },
  { path: "/#/bakery/boulangerie-fossey" },
  { path: "/#/bakery/l-atelier-fossey" },
  { path: "/#/bakery/boulangerie-de-fosses-la-tradition-franaise" },
  { path: "/#/bakery/la-ptite-boulange" },
  { path: "/#/bakery/la-craquante-montgeron" },
  { path: "/#/bakery/au-fournil-pixien" },
  { path: "/#/bakery/les-viviers" },
  { path: "/#/bakery/joigny-sur-meuse" },
  { path: "/#/bakery/wallois-marie-didier" },
  { path: "/#/bakery/boulangerie-anthony-hersog" },
  { path: "/#/bakery/boulangerie-anthony-duquenoy" },
  { path: "/#/bakery/boulangerie-anthony-ptisserie" },
  { path: "/#/bakery/boulangerie-lessentiel--anthony-bosson" },
  { path: "/#/bakery/lessentiel-boulangerie" },
  { path: "/#/bakery/la-fort-le-roi" },
  { path: "/#/bakery/boulangerie-lechevrel" },
  { path: "/#/bakery/boulangerie-ptisserie-monnois" },
  { path: "/#/bakery/berger-jrme" },
  { path: "/#/bakery/boulangerie-le-martrat" },
  { path: "/#/bakery/boulanger-ptissier-maison-colin" },
  { path: "/#/bakery/crecy-sur-serre-old-german-military-cemetery" },
  { path: "/#/bakery/mairie-de-crcy-sur-serre" },
  { path: "/#/bakery/crsia-crecy-sur-serre" },
  { path: "/#/bakery/eleclerc-drive-neuville-saint-amand" },
  { path: "/#/bakery/boulangerie-le-b-100-bio-beaune" },
  { path: "/#/bakery/le-fournil-des-loges" },
  { path: "/#/bakery/mairie-de-le-nouvion-en-thirache" },
  { path: "/#/bakery/base-de-loisirs-de-lastree--le-nouvion-en-thirache" },
  { path: "/#/bakery/piscine-le-nouvion-en-thierache" },
  { path: "/#/bakery/wada-et-fils" },
  { path: "/#/bakery/la-case-pain" },
  { path: "/#/bakery/charlier-pere-et-fils" },
  { path: "/#/bakery/boulanger-lisieux" },
  { path: "/#/bakery/boulangerie-ptisserie-dravigny" },
  { path: "/#/bakery/suzy-et-arlette" },
  { path: "/#/bakery/boulangerie-feuillette" },
  { path: "/#/bakery/artisan-boulanger-viennoisier-les-dlices-de-crpy" },
  { path: "/#/bakery/boulangerie-jean-luc-rosso" },
  { path: "/#/bakery/la-boulangerie-de-marcy--maison-blache" },
  { path: "/#/bakery/pleau-rodolphe" },
  { path: "/#/bakery/boulangerie-legendre-guyancourt-maison-legendre" },
  { path: "/#/bakery/boulangerie-demessemacker" },
  { path: "/#/bakery/boulangerie-lejeune-cdric" },
  { path: "/#/bakery/mairie-de-brancourt-en-laonnois" },
  { path: "/#/bakery/boulangerie-quentin-et-emeline" },
  { path: "/#/bakery/la-mie-du-pain" },
  { path: "/#/bakery/boulangerie-moulin-de-la-bresse" },
  { path: "/#/bakery/boulangerie-jolibois" },
  { path: "/#/bakery/eurl-pm-parent-matthieu" },
  { path: "/#/bakery/senlecque-eric-michel" },
  { path: "/#/bakery/le-fournil-de-luzge" },
  { path: "/#/bakery/boulangerie-monnet" },
  { path: "/#/bakery/ptisserie-chocolaterie-monnet" },
  { path: "/#/bakery/boulangerie-monet" },
  { path: "/#/bakery/boulangerie-les-petits-loups" },
  { path: "/#/bakery/boulangerie-ptisserie-da-costa" },
  { path: "/#/bakery/boulangerie-buret" },
  { path: "/#/bakery/burel-marc" },
  { path: "/#/bakery/le-fournil-du-burel-maison-lazzeri" },
  { path: "/#/bakery/mairie-daulnois-sous-laon" },
  { path: "/#/bakery/bread-and-tradition" },
  { path: "/#/bakery/latelier-des-saveurs" },
  { path: "/#/bakery/au-fournil-mousterien" },
  { path: "/#/bakery/anciaux-christophe" },
  { path: "/#/bakery/boulangerie-renoit" },
  { path: "/#/bakery/boulangerie-des-templiers" },
  { path: "/#/bakery/boulangerie-du-donjon-de-septmonts" },
  { path: "/#/bakery/le-fournil-detreux" },
  { path: "/#/bakery/boulangerie-fontenelle" },
  { path: "/#/bakery/intermarch-super-ressons-le-long" },
  { path: "/#/bakery/les-serres-de-rouvroy" },
  { path: "/#/bakery/le-fournil-bruxellois" },
  { path: "/#/bakery/domaine-les-fontaines" },
  { path: "/#/bakery/tomco-dijonahuy" },
  { path: "/#/bakery/les-comptoirs-de-la-bio--dijon" },
  { path: "/#/bakery/boulangerie-leroy-monti" },
  { path: "/#/bakery/boulangerie-havin" },
  { path: "/#/bakery/leroy-sebastien" },
  { path: "/#/bakery/boulangerie-ptisserie-lisa-et-julien-leroy" },
  { path: "/#/bakery/boulangerie-ptisserie-joanna-et-alexis-gratpanche" },
  { path: "/#/bakery/monceau-fleurs" },
  { path: "/#/bakery/chez-chris" },
  { path: "/#/bakery/au-bon-pain" },
  { path: "/#/bakery/latelier-de-batrice" },
  { path: "/#/bakery/boulangerie-du-mont-olympe-chocolaterie-carr-du-monde" },
  { path: "/#/bakery/maison-billard--ptisserie-boulangerie-chocolaterie" },
  { path: "/#/bakery/le-secret-des-pains--71590-gergy--lisa-et-maximilien-marchal-glain" },
  { path: "/#/bakery/mairie-de-bohain-en-vermandois" },
  { path: "/#/bakery/boulangerie--ptisserie-christian-lambert" },
  { path: "/#/bakery/boulangerie-vhn" },
  { path: "/#/bakery/boulangerie-maison-vivier--tignieu" },
  { path: "/#/bakery/maison-chanvillard--boulanger-ptissier-chocolatier-glacier" },
  { path: "/#/bakery/rouillon-arnaud" },
  { path: "/#/bakery/boulangerie-tonnelle" },
  { path: "/#/bakery/atout-pains" },
  { path: "/#/bakery/pouilly-david" },
  { path: "/#/bakery/maison-pouilly" },
  { path: "/#/bakery/mairie-de-vesles-et-caumont" },
  { path: "/#/bakery/boulangerie-patisserie-aurore-alexandre" },
  { path: "/#/bakery/coudrat-marc" },
  { path: "/#/bakery/maison-bourguignon" },
  { path: "/#/bakery/ptisserie-bourguignon-metz" },
  { path: "/#/bakery/le-puy-des-delices" },
  { path: "/#/bakery/boulangerie-du-moulin" },
  { path: "/#/bakery/la-boulangerie-de-launois" },
  { path: "/#/bakery/groupe-hospitalier-les-cheminots" },
  { path: "/#/bakery/college-le-bocage" },
  { path: "/#/bakery/romanee--au-bocage-du-lac" },
  { path: "/#/bakery/relais-le-bocage" },
  { path: "/#/bakery/piscine-du-bocage" },
  { path: "/#/bakery/latelier-des-gourmands" },
  { path: "/#/bakery/montaiguet-en-forez" },
  { path: "/#/bakery/mairie-de-montaigut-en-forez" },
  { path: "/#/bakery/mairie-de-garnat-sur-engivre" },
  { path: "/#/bakery/boulangerie-chazelle-boulangerie-de-lglise" },
  { path: "/#/bakery/au-petrin-castellucien" },
  { path: "/#/bakery/la-chapelle-aux-vins" },
  { path: "/#/bakery/boulangerie-ptisserie-chatillonnaise-patrick-riquelme" },
  { path: "/#/bakery/smia" },
  { path: "/#/bakery/la-grange-aux-pains" },
  { path: "/#/bakery/la-carte" },
  { path: "/#/bakery/triboulet-sebastien" },
  { path: "/#/bakery/mairie-de-saint-priest-en-murat" },
  { path: "/#/bakery/mairie-de-neuilly-en-donjon" },
  { path: "/#/bakery/boulangerie-le-panier" },
  { path: "/#/bakery/boulangerie-bio-saint-menoux" },
  { path: "/#/bakery/mairie-de-saligny-sur-roudon" },
  { path: "/#/bakery/la-boulange-pineaumeyniel" },
  { path: "/#/bakery/boulangerie-ptisserie-hunerbein" },
  { path: "/#/bakery/cole-des-mines-de-saint-tienne" },
  { path: "/#/bakery/meniger-jordane" },
  { path: "/#/bakery/dimalice-merveilles" },
  { path: "/#/bakery/boulangerie-s-droulers" },
  { path: "/#/bakery/market-bourbon-larchambault" },
  { path: "/#/bakery/casino-bourbon-larchambault" },
  { path: "/#/bakery/thermes-de-bourbon-larchambault" },
  { path: "/#/bakery/boulangerie-maizel" },
  { path: "/#/bakery/pains-et-gourmandises-de-la-basilique" },
  { path: "/#/bakery/pani-dlice" },
  { path: "/#/bakery/tradition-nivault" },
  { path: "/#/bakery/boulangerie-patisserie-wernet-alain" },
  { path: "/#/bakery/boulangerie-paul-thionville-longwy" },
  { path: "/#/bakery/boulangerie-linster" },
  { path: "/#/bakery/mourier-franck" },
  { path: "/#/bakery/fournil-des-saveurs" },
  { path: "/#/bakery/boulangerie-ptisserie-pourias" },
  { path: "/#/bakery/la-boule-carre-lphant" },
  { path: "/#/bakery/le-plaisir-du-pain-rafflegeau-pascal" },
  { path: "/#/bakery/boulangerie-cottret-vesseaux" },
  { path: "/#/bakery/boulangerie-dcroissant" },
  { path: "/#/bakery/au-ptrin-de-vitrey" },
  { path: "/#/bakery/mairie-de-saint-lger-sur-vouzance" },
  { path: "/#/bakery/boulangerie-patisserie-duboux" },
  { path: "/#/bakery/maison-bellamy-loc" },
  { path: "/#/bakery/boulangerie-besson" },
  { path: "/#/bakery/boulangerie-patisserie-besson" },
  { path: "/#/bakery/boulangerie-patisserie-bessou" },
  { path: "/#/bakery/boulangerie-picarles" },
  { path: "/#/bakery/micheau-sebastien" },
  { path: "/#/bakery/boulangerie-sendra" },
  { path: "/#/bakery/mairie-de-saint-rmy-en-rollat" },
  { path: "/#/bakery/lamour-du-pain" },
  { path: "/#/bakery/boulangerie-lepionnet" },
  { path: "/#/bakery/boulangerie-ptisserie-michel-dudot" },
  { path: "/#/bakery/tholin" },
  { path: "/#/bakery/boulangerie-romane-et-mickal" },
  { path: "/#/bakery/boulangerie-au-pain-dantan" },
  { path: "/#/bakery/boulangerie-patisserie-damien-vauthier" },
  { path: "/#/bakery/camping-le-mayet-de-montagne" },
  { path: "/#/bakery/intermarch-super-le-mayet-de-montagne-et-drive" },
  { path: "/#/bakery/le-7me-pch" },
  { path: "/#/bakery/le-pain-simplement--artisan-boulanger" },
  { path: "/#/bakery/boulangerie-louise" },
  { path: "/#/bakery/boulangerie-la-griotine" },
  { path: "/#/bakery/le-7me-pch-saint-loup-ganges" },
  { path: "/#/bakery/le-fournil-de-saint-loup-bio--litzellmann" },
  { path: "/#/bakery/boulangerie-forget-jean-luc" },
  { path: "/#/bakery/la-mie-victorienne" },
  { path: "/#/bakery/dumas-ludovic" },
  { path: "/#/bakery/boulangerie-blondel" },
  { path: "/#/bakery/au-mille-pates" },
  { path: "/#/bakery/sarl-boulangerie-boyer" },
  { path: "/#/bakery/l-artisan-du-pain" },
  { path: "/#/bakery/les-dlices-de-chamblet" },
  { path: "/#/bakery/mairie-de-montay-sur-allier" },
  { path: "/#/bakery/tartines-gourmandises" },
  { path: "/#/bakery/verneuil-en-bio--magasin-bio-normandie--bio-local-verneuil-sur-avre" },
  { path: "/#/bakery/boulangerie-ar-bara" },
  { path: "/#/bakery/la-place-gourmande" },
  { path: "/#/bakery/htel-restaurant-campanile-vichy--bellerive-sur-allier" },
  { path: "/#/bakery/mairie-de-bellerive-sur-allier" },
  { path: "/#/bakery/boulangerie-ptisserie-la-pommeraie" },
  { path: "/#/bakery/au-four-et-au-moulin" },
  { path: "/#/bakery/la-fourne-de-lartisan" },
  { path: "/#/bakery/luneau-damien" },
  { path: "/#/bakery/boulangerie-rouchier-steve" },
  { path: "/#/bakery/le-pain-de-la-fontaine" },
  { path: "/#/bakery/farine-et-chocolat" },
  { path: "/#/bakery/vasco-pereira-david" },
  { path: "/#/bakery/boulangerie-baudet" },
  { path: "/#/bakery/les-artisans-reunis--40180" },
  { path: "/#/bakery/gout-nivoix-jean-marc" },
  { path: "/#/bakery/chez-lami-mich" },
  { path: "/#/bakery/r-this" },
  { path: "/#/bakery/les-petits-gourmands" },
  { path: "/#/bakery/le-ptit-beurri" },
  { path: "/#/bakery/gourmandises-et-tradition" },
  { path: "/#/bakery/boulanger-lyon--saint-priest" },
  { path: "/#/bakery/maison-lagoutte" },
  { path: "/#/bakery/boulanger-de-la-gare" },
  { path: "/#/bakery/boulangerie--ptisserie-albert-busser" },
  { path: "/#/bakery/boulangerie-patisserie-traiteur" },
  { path: "/#/bakery/contrle-technique-villefranche-dallier" },
  { path: "/#/bakery/au-fournil-du-breuil" },
  { path: "/#/bakery/le-fournil-du-breuil" },
  { path: "/#/bakery/boulanger-vichy" },
  { path: "/#/bakery/co-pain-et-a-mie" },
  { path: "/#/bakery/marchand-patrice" },
  { path: "/#/bakery/mairie-de-jaligny-sur-besbre" },
  { path: "/#/bakery/mairie-de-saint-grand-de-vaux" },
  { path: "/#/bakery/mairie-de-varennes-sur-tche" },
  { path: "/#/bakery/boulangerie-le-hrisson" },
  { path: "/#/bakery/la-noyantise" },
  { path: "/#/bakery/les-chandelles" },
  { path: "/#/bakery/bb-boulanger" },
  { path: "/#/bakery/boulangerie-ptisserie-mr" },
  { path: "/#/bakery/au-fournil-de-bagneaux" },
  { path: "/#/bakery/boulangerie-la-chapelle" },
  { path: "/#/bakery/auroy-jean-luc" },
  { path: "/#/bakery/proxi--le-fournil-de-laubespain" },
  { path: "/#/bakery/centre-minier-de-faymoreau" },
  { path: "/#/bakery/scelles-richard-banette" },
  { path: "/#/bakery/boulangerie-gimel-didier" },
  { path: "/#/bakery/mirambeau-jean-jacques" },
  { path: "/#/bakery/boulangerie-place-monge--marie-boucherot" },
  { path: "/#/bakery/le-fournil-derbray--boulangerie-ptisserie" },
  { path: "/#/bakery/hopital-de-beaune" },
  { path: "/#/bakery/boulangerie-martine-et-eric-richard" },
  { path: "/#/bakery/htel-de-ville-de-beaune" },
  { path: "/#/bakery/boulangerie-berthe-jeanne-darc" },
  { path: "/#/bakery/boulangerie-berthon-mickal" },
  { path: "/#/bakery/boulangerie-patisserie-bertin" },
  { path: "/#/bakery/le-refuge-des-gourmands" },
  { path: "/#/bakery/la-lauragaise" },
  { path: "/#/bakery/toureille-frdric" },
  { path: "/#/bakery/la-petite-boulangerie" },
  { path: "/#/bakery/boulangerie-alain-chapeau" },
  { path: "/#/bakery/boulangerie-payrat" },
  { path: "/#/bakery/la-fourne-du-chapeau-rouge" },
  { path: "/#/bakery/au-fournil-dygrande" },
  { path: "/#/bakery/le-moulin-darthur" },
  { path: "/#/bakery/boulanger-grenoble-echirolles" },
  { path: "/#/bakery/villeneuve-sur-allier" },
  { path: "/#/bakery/mairie-de-villeneuve-sur-allier" },
  { path: "/#/bakery/boulangerie-de-premilhat" },
  { path: "/#/bakery/boulangerie-patisserie-du-ruisseau" },
  { path: "/#/bakery/dumet-jean-claude" },
  { path: "/#/bakery/mairie-de-saint-didier-en-donjon" },
  { path: "/#/bakery/la-planche-a-pain" },
  { path: "/#/bakery/maupin-emeric" },
  { path: "/#/bakery/boulangerie-saint-leonard" },
  { path: "/#/bakery/le-panis" },
  { path: "/#/bakery/fournil-gourmand" },
  { path: "/#/bakery/boulangerie-snacking-murat" },
  { path: "/#/bakery/la-boulangerie-jouvenon" },
  { path: "/#/bakery/boulangerie-maillet" },
  { path: "/#/bakery/les-delices-des-maillets" },
  { path: "/#/bakery/maillet-frres-sarl" },
  { path: "/#/bakery/la-belle-dchette" },
  { path: "/#/bakery/boulangerie-de-vicq-sur-nahon" },
  { path: "/#/bakery/au-pain-chaud" },
  { path: "/#/bakery/boulangerie-ptisserie-franck-tonnelet" },
  { path: "/#/bakery/jean-luc-bost" },
  { path: "/#/bakery/boulangerie-ptisserie-dabrest" },
  { path: "/#/bakery/la-grange-a-pains" },
  { path: "/#/bakery/boulangerie-christophe" },
  { path: "/#/bakery/la-maison-des-dlices" },
  { path: "/#/bakery/les-douceurs-de-la-leve" },
  { path: "/#/bakery/boulangerie-ange" },
  { path: "/#/bakery/la-maie-du-village" },
  { path: "/#/bakery/market-cosne-dallier" },
  { path: "/#/bakery/mairie-de-cosne-d-allier" },
  { path: "/#/bakery/lglise-de-la-madeleine" },
  { path: "/#/bakery/la-boulangerie-davermes" },
  { path: "/#/bakery/snc-sciandra-devaux" },
  { path: "/#/bakery/les-gourmandises-de-julie-et-christophe" },
  { path: "/#/bakery/mouillet-alban" },
  { path: "/#/bakery/les-delices-de-saint-germain" },
  { path: "/#/bakery/yoann-de-contet" },
  { path: "/#/bakery/boulangerie-rg" },
  { path: "/#/bakery/boulangerie-rouzier" },
  { path: "/#/bakery/bakery-paquier-jrmy-and-chloe" },
  { path: "/#/bakery/boulangerie-ptisserie-retailleau" },
  { path: "/#/bakery/boulangerie-patisserie-des-dames" },
  { path: "/#/bakery/boulangerie-bertrand-legros" },
  { path: "/#/bakery/boulangerie-patisserie-couzon" },
  { path: "/#/bakery/boulangerie-vial-xavier" },
  { path: "/#/bakery/naan-boulangerie-ptisserie--villeurbanne-la-soie" },
  { path: "/#/bakery/boulangerie-les-dlices-de-marjorie" },
  { path: "/#/bakery/la-gourmandine" },
  { path: "/#/bakery/boulangerie-ptisserie-du-lac" },
  { path: "/#/bakery/ratier-laurent-alain" },
  { path: "/#/bakery/l-instant-gourmand" },
  { path: "/#/bakery/aux-delices-de-bonneuil" },
  { path: "/#/bakery/boulangerie-gots-et-saveurs" },
  { path: "/#/bakery/pains-et-gourmandises" },
  { path: "/#/bakery/pottier-eric" },
  { path: "/#/bakery/la-mie-qui-roule" },
  { path: "/#/bakery/boulangerie-ptisserie-bourguignon" },
  { path: "/#/bakery/soyer-mathew" },
  { path: "/#/bakery/boulangerie-ptisserie-gury" },
  { path: "/#/bakery/lopez-romain" },
  { path: "/#/bakery/blind" },
  { path: "/#/bakery/the-blind-piper" },
  { path: "/#/bakery/la-brioche-de-vendrennes" },
  { path: "/#/bakery/boulangerie-ptisserie-lami-de-pin" },
  { path: "/#/bakery/boulangerie-daniel-vily" },
  { path: "/#/bakery/au-cygne-gourmand" },
  { path: "/#/bakery/au-fournil-du-pin" },
  { path: "/#/bakery/boulangerie-st-nicolas" },
  { path: "/#/bakery/laurent-jeremy" },
  { path: "/#/bakery/mairie-de-bessay-sur-allier" },
  { path: "/#/bakery/lepis-bourbonnais" },
  { path: "/#/bakery/aux-dlices-de-thiel" },
  { path: "/#/bakery/lpicerie-au-fournil" },
  { path: "/#/bakery/boulangerie-sorbier" },
  { path: "/#/bakery/mairie-de-paray-sous-briailles" },
  { path: "/#/bakery/boulangerie-ptisserie--le-fournil-de-saint-caprais" },
  { path: "/#/bakery/artisan-boulanger-gabriel-k" },
  { path: "/#/bakery/mairie-de-varennes-sur-allier" },
  { path: "/#/bakery/le-fournil-de-lna" },
  { path: "/#/bakery/lger-philippe" },
  { path: "/#/bakery/mairie-de-dompierre-sur-besbre" },
  { path: "/#/bakery/objectifcode--centre-dexamen-du-code-de-la-route-dompierre-sur-besbre" },
  { path: "/#/bakery/crdit-agricole-centre-france--dompierre-sur-besbre" },
  { path: "/#/bakery/le-fournil-de-jean--avignon-durand" },
  { path: "/#/bakery/mairie-de-pierrefitte-sur-loire" },
  { path: "/#/bakery/aire-de-pierrefitte-sur-loire-nord" },
  { path: "/#/bakery/sebastien-dupont--44390" },
  { path: "/#/bakery/boulangerie-hoisnard-denis" },
  { path: "/#/bakery/texier-pascal" },
  { path: "/#/bakery/la-boulange-lily" },
  { path: "/#/bakery/boulangerie-gladines" },
  { path: "/#/bakery/aux-dlices-de-thse" },
  { path: "/#/bakery/moulin-de-flr" },
  { path: "/#/bakery/le-fournil-des-mes" },
  { path: "/#/bakery/boulangerie-ptisserie-dewulf" },
  { path: "/#/bakery/le-coin-des-gourmands" },
  { path: "/#/bakery/mousselin-deregnaucourt-lucie" },
  { path: "/#/bakery/boulangerie-mondino" },
  { path: "/#/bakery/boulangerie-ptisserie-marcoux" },
  { path: "/#/bakery/boulangerie-colmar" },
  { path: "/#/bakery/boulangerie-imhoff-patisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-la-ptite-rustique" },
  { path: "/#/bakery/boulangerie-patisserie-kretz-jean-leon" },
  { path: "/#/bakery/ptisserie-charles-schmitt--boutique-hpital-schweitzer" },
  { path: "/#/bakery/andrieux" },
  { path: "/#/bakery/le-boulanger-de-mirabeau" },
  { path: "/#/bakery/la-porteuse-de-pains" },
  { path: "/#/bakery/boulangerie-de-la-citadelle" },
  { path: "/#/bakery/le-dauphin-gourmand" },
  { path: "/#/bakery/nathalie-et-marcel-bas" },
  { path: "/#/bakery/le-lys-dor-orlans" },
  { path: "/#/bakery/boulangerie-saint-pierre" },
  { path: "/#/bakery/boulangerie-lecomte-saint-pierre" },
  { path: "/#/bakery/boulangerie-souvignet" },
  { path: "/#/bakery/aux-dlices-de-sonia-et-dom" },
  { path: "/#/bakery/palais-saint-lazare" },
  { path: "/#/bakery/sas-louis" },
  { path: "/#/bakery/au-petit-grain-de-bl" },
  { path: "/#/bakery/boulangerie-claret" },
  { path: "/#/bakery/auto-ecole-le-chaffaut" },
  { path: "/#/bakery/blanc-pascal" },
  { path: "/#/bakery/la-fourne-de-joseph" },
  { path: "/#/bakery/boulangerie-la-paluarde" },
  { path: "/#/bakery/le-four-bois" },
  { path: "/#/bakery/mairie-saint-vincent-les-forts" },
  { path: "/#/bakery/dorlise" },
  { path: "/#/bakery/le-jardin-du-val" },
  { path: "/#/bakery/la-valle-village" },
  { path: "/#/bakery/mairie-htel-de-ville-fontenay" },
  { path: "/#/bakery/auchan-hypermarch-fontenay-sous-bois" },
  { path: "/#/bakery/boulangerie-saint-laurent" },
  { path: "/#/bakery/lallemagnette-boulangerie-david-soubie" },
  { path: "/#/bakery/la-mie-do-r" },
  { path: "/#/bakery/fabris-jean-marie" },
  { path: "/#/bakery/pascal-boulangerie-patisserie" },
  { path: "/#/bakery/boulangerie-lessault-christophe" },
  { path: "/#/bakery/antoine-co" },
  { path: "/#/bakery/boulangerie-artisanale-le-fils-du-boulanger" },
  { path: "/#/bakery/boulangerie-millet-vaulx-en-velin-avenue-roger-salengro" },
  { path: "/#/bakery/boulangerie-millet-vaulx-en-velin-avenue-eugne-hnaff" },
  { path: "/#/bakery/boulangerie-millet-vaulx-en-velin-rue-emile-zola" },
  { path: "/#/bakery/boulangerie-millet-vaulx-en-velin-rue-de-la-rpublique" },
  { path: "/#/bakery/linstant-gourmand" },
  { path: "/#/bakery/au-croissant-dor" },
  { path: "/#/bakery/lescale-boulangre" },
  { path: "/#/bakery/boulangerie-saint-jacques" },
  { path: "/#/bakery/run-ptisserie-boulangerie-saint-jacques" },
  { path: "/#/bakery/guerrida-house" },
  { path: "/#/bakery/l-atelier-de-louise" },
  { path: "/#/bakery/boulangerie-ptisserie-aux-trois-petits-pains" },
  { path: "/#/bakery/boulangerie-le-tertre" },
  { path: "/#/bakery/the-palloy-bakeries-street" },
  { path: "/#/bakery/ptisserie-au-lion-dor" },
  { path: "/#/bakery/les-dlices-de-lucas" },
  { path: "/#/bakery/ma-mie-gourmande" },
  { path: "/#/bakery/boulangerie-manel" },
  { path: "/#/bakery/sas-boulangerie-manet" },
  { path: "/#/bakery/manlin-le-boulanger-de-jean-mac" },
  { path: "/#/bakery/boulangerie-du-chapeau-rouge" },
  { path: "/#/bakery/boulangerie-nicolas-m-et-m" },
  { path: "/#/bakery/boulanger-toulon--la-garde" },
  { path: "/#/bakery/la-perle" },
  { path: "/#/bakery/latelier-ginestas--pains--ptisseries--produits-locaux" },
  { path: "/#/bakery/boulangerie-au-pain-de-la-valle" },
  { path: "/#/bakery/boulangerie-des-oliviers" },
  { path: "/#/bakery/le-fournil-dallos" },
  { path: "/#/bakery/boulangerie-maison-marquise" },
  { path: "/#/bakery/boulangerie-maison-neves" },
  { path: "/#/bakery/boulangerie-brun" },
  { path: "/#/bakery/les-traditions-de-beynes" },
  { path: "/#/bakery/une-part-de-rve" },
  { path: "/#/bakery/maison-de-lartisan" },
  { path: "/#/bakery/le-pain-des-angles-boulangerie-ptisserie-artisanale" },
  { path: "/#/bakery/ptisserie-supervie" },
  { path: "/#/bakery/boulanger-anglet" },
  { path: "/#/bakery/passion-gourmande" },
  { path: "/#/bakery/ptisserie-boulangerie-chez-ptit-mauss" },
  { path: "/#/bakery/boulangerie-de-lerdre" },
  { path: "/#/bakery/trs-alpain" },
  { path: "/#/bakery/boulangerie-castellane" },
  { path: "/#/bakery/boulangerie-de-castellane" },
  { path: "/#/bakery/aux-delices-de-volonne" },
  { path: "/#/bakery/boulangerie-pains-sucre" },
  { path: "/#/bakery/boulangerie-ptisserie-fretes-garel" },
  { path: "/#/bakery/boulangerie-ptisserie-du-cappeville" },
  { path: "/#/bakery/le-marquis-dambre" },
  { path: "/#/bakery/boulangerie-aux-cinq-grains" },
  { path: "/#/bakery/boulangerie-du-grand-martroy" },
  { path: "/#/bakery/maison-pichard" },
  { path: "/#/bakery/boulangerie-lodie-et-david" },
  { path: "/#/bakery/les-pains-de-la-tamelire" },
  { path: "/#/bakery/le-palais-dor" },
  { path: "/#/bakery/boulangerie-ptisserie-appeyroux" },
  { path: "/#/bakery/boulangerie-le-moulin-des-cabanes" },
  { path: "/#/bakery/la-fourne-comisso" },
  { path: "/#/bakery/boulangerie-de-banon" },
  { path: "/#/bakery/la-boulange-et-steph" },
  { path: "/#/bakery/maison-jorge" },
  { path: "/#/bakery/maison-jorge-leroy" },
  { path: "/#/bakery/sarl-boulangerie-patisserie-monin" },
  { path: "/#/bakery/boulangerie-della-casa" },
  { path: "/#/bakery/boulangerie-brunet" },
  { path: "/#/bakery/camping-du-lac" },
  { path: "/#/bakery/boulangerie-maison-fontaine" },
  { path: "/#/bakery/boulangerie-fontaine-bernecoli-la-boulangerie-du-coin" },
  { path: "/#/bakery/boulangerie-fontaine" },
  { path: "/#/bakery/boulangerie-st-vincent" },
  { path: "/#/bakery/maison-familiale-rurale" },
  { path: "/#/bakery/boulangerie-cajan" },
  { path: "/#/bakery/lefrre-patrick" },
  { path: "/#/bakery/boulangerie-la-mie-chalonnaise" },
  { path: "/#/bakery/brasserie-o-saint-martin" },
  { path: "/#/bakery/boulangerie-saint-martin" },
  { path: "/#/bakery/cole-internationale-de-boulangerie" },
  { path: "/#/bakery/boulangerie-des-marronniers" },
  { path: "/#/bakery/boulangerie-au-duc-de-rambouillet" },
  { path: "/#/bakery/boulangerie-ptisserie-navarro" },
  { path: "/#/bakery/boulangerie-ptisserie--clment-baptiste" },
  { path: "/#/bakery/moulin-melou" },
  { path: "/#/bakery/le-moulin-boulangerie-allirol-boulangerie-ptisserie-chocolaterie-traiteur" },
  { path: "/#/bakery/sarl-louis-dor" },
  { path: "/#/bakery/boulanger-saint-etienne--villars" },
  { path: "/#/bakery/boulangerie-dumas" },
  { path: "/#/bakery/boulangerie-saint-crpain" },
  { path: "/#/bakery/la-mie-mariotte" },
  { path: "/#/bakery/boulangerie-ptisserie-guichard-meyreuil" },
  { path: "/#/bakery/boulangerie--ptisserie--salon-de-th-de-ltoile" },
  { path: "/#/bakery/boulangerie-de-letoile" },
  { path: "/#/bakery/boulangerie-ptisserie-la-roche" },
  { path: "/#/bakery/camping-les-bouleaux--la-chapelle-en-valgaudemar" },
  { path: "/#/bakery/boulangerie-la-chapelle-des-dlices" },
  { path: "/#/bakery/le-fournil-belloquois" },
  { path: "/#/bakery/la-boulangerie-de-la-chapelle" },
  { path: "/#/bakery/aux-dlices-de-neffis" },
  { path: "/#/bakery/edelweiss-boulanger-patisserie" },
  { path: "/#/bakery/cest-pain-dla-tarte" },
  { path: "/#/bakery/boulangerie-legrand" },
  { path: "/#/bakery/la-grandboulangerie" },
  { path: "/#/bakery/market-saint-bonnet-en-champsaur" },
  { path: "/#/bakery/centre-de-sant-dentaire-saint-bonnet-en-champsaur" },
  { path: "/#/bakery/boulangerie-les-embruns" },
  { path: "/#/bakery/aux-petits-godon" },
  { path: "/#/bakery/le-fournil-des-crins" },
  { path: "/#/bakery/la-contremarche" },
  { path: "/#/bakery/boulangerie-lieval-gap" },
  { path: "/#/bakery/le-fournil-savinois" },
  { path: "/#/bakery/association-aronautique-daspres-sur-buch" },
  { path: "/#/bakery/michel-mose" },
  { path: "/#/bakery/boulangerie-ptisserie-richard" },
  { path: "/#/bakery/la-boulangerie" },
  { path: "/#/bakery/office-de-tourisme-de-serre-chevalier-la-salle-les-alpes" },
  { path: "/#/bakery/le-kiosque-gourmand" },
  { path: "/#/bakery/le-_-clach" },
  { path: "/#/bakery/boulangerie-de-patrick-et-batrice-rialland" },
  { path: "/#/bakery/boulangerie-tony-lux" },
  { path: "/#/bakery/la-corbeille-a-pains" },
  { path: "/#/bakery/merlin-pain-pain" },
  { path: "/#/bakery/boulangerie-ptisserie-rambaud" },
  { path: "/#/bakery/boulangerie-saint-sauveur" },
  { path: "/#/bakery/boutique-de-st-sauveur-de-la-ptisserie-mousnier-le-yeu" },
  { path: "/#/bakery/boulangerie-costechareyre" },
  { path: "/#/bakery/le-fournil-de-st-sauveur" },
  { path: "/#/bakery/boulanger-la-roche-sur-yon" },
  { path: "/#/bakery/maison-barbarit" },
  { path: "/#/bakery/limperial-boulangerie-ptisserie-chocolaterie" },
  { path: "/#/bakery/la-roche-de-sauterre" },
  { path: "/#/bakery/le-fournil-de-la-gravette" },
  { path: "/#/bakery/le-pain-des-cimes-1400--ville-vieille" },
  { path: "/#/bakery/les-temps-du-corps" },
  { path: "/#/bakery/boulangerie-du-cristol" },
  { path: "/#/bakery/boulangerie-patisserie-l-alpain" },
  { path: "/#/bakery/office-de-tourisme-de-molines-en-queyras" },
  { path: "/#/bakery/intersport--molines-en-queyras" },
  { path: "/#/bakery/fromagerie-de-chteau-queyras" },
  { path: "/#/bakery/boulangerie-ptisserie-ledelweiss" },
  { path: "/#/bakery/guibert-jean-charles" },
  { path: "/#/bakery/boulangerie-ptisserie-maison-lamotte" },
  { path: "/#/bakery/boulangerie-de-lorrez" },
  { path: "/#/bakery/boulangerie--bziers" },
  { path: "/#/bakery/boulangerie-le-fournil-de-la-treille--bziers" },
  { path: "/#/bakery/boulangerie-bousquet" },
  { path: "/#/bakery/le-fournil-de-la-font-neuve" },
  { path: "/#/bakery/le-fournil-dars-en-re--17590" },
  { path: "/#/bakery/maison-lemon" },
  { path: "/#/bakery/dchetterie-de-barret-sur-mouge" },
  { path: "/#/bakery/boulangerie-housset-marigny" },
  { path: "/#/bakery/boulangerie-gautray" },
  { path: "/#/bakery/fournil-de-trayeux-boulangerie-lacelle--treignac" },
  { path: "/#/bakery/boulangerie-gabriel" },
  { path: "/#/bakery/fournil-des-comtes" },
  { path: "/#/bakery/boulangerie-ptisserie-orustique" },
  { path: "/#/bakery/aux-delices-gourmands-le-tutti-fruitti" },
  { path: "/#/bakery/le-fournil-de-sacha" },
  { path: "/#/bakery/boulanger-grand-vitrolles" },
  { path: "/#/bakery/le-four-a-bois" },
  { path: "/#/bakery/boulanger-plan-de-campagne" },
  { path: "/#/bakery/le-fournil-de-sainte-colombe" },
  { path: "/#/bakery/la-mie-qui-chante" },
  { path: "/#/bakery/boulangerie-les-trois-petits-bannetons" },
  { path: "/#/bakery/le-petit-fournil-du-suran" },
  { path: "/#/bakery/boulangerie-larroque-lauzerte" },
  { path: "/#/bakery/de-nardi-boulangerie-ptisserie" },
  { path: "/#/bakery/boulangerie-du-champsaur" },
  { path: "/#/bakery/chateauneuf-du-pain" },
  { path: "/#/bakery/o-delices-de-la-boul-ange-r-sarl" },
  { path: "/#/bakery/affigliati" },
  { path: "/#/bakery/boulangerie-megardon-jean-marc-jean-marc" },
  { path: "/#/bakery/boulangerie-oddos" },
  { path: "/#/bakery/connexion-partenaire-boulanger-unieux" },
  { path: "/#/bakery/boulangerie-dorpierre-vival" },
  { path: "/#/bakery/boulangerie-ptisserie-ricou" },
  { path: "/#/bakery/les-fous-de-la-boulange" },
  { path: "/#/bakery/boulangerie-oui-mais-plus-philis" },
  { path: "/#/bakery/atelier-des-saveurs" },
  { path: "/#/bakery/maison-polka--boulangerie--ptisserie--snacking" },
  { path: "/#/bakery/la-bohme" },
  { path: "/#/bakery/boulangerie-ptisserie-mallorant" },
  { path: "/#/bakery/boulangerie-de-lepine" },
  { path: "/#/bakery/le-moulin-de-lpine" },
  { path: "/#/bakery/le-pain-dor" },
  { path: "/#/bakery/chez-paillat-le-boulanger" },
  { path: "/#/bakery/pains-patisserie-au-pain-qui-fume" },
  { path: "/#/bakery/boulangerie-amy" },
  { path: "/#/bakery/boulangerie-ptisserie-teleguei" },
  { path: "/#/bakery/les-gourmandises-de-poulaines" },
  { path: "/#/bakery/la-boulangerie-saint-pierre" },
  { path: "/#/bakery/boulangerie-du-phare" },
  { path: "/#/bakery/le-sauze-du-lac" },
  { path: "/#/bakery/les-saveurs-du-mdoc" },
  { path: "/#/bakery/boulangerie-hlne" },
  { path: "/#/bakery/patisserie-rousset-jc" },
  { path: "/#/bakery/la-bonheure" },
  { path: "/#/bakery/les-dlices-deoures" },
  { path: "/#/bakery/boulangerie-de-la-faurie" },
  { path: "/#/bakery/la-parisienne-saint-germain" },
  { path: "/#/bakery/boulangerie-la-parisienne" },
  { path: "/#/bakery/boulangerie-saint-nicolas" },
  { path: "/#/bakery/office-de-tourisme-des-hautes-valles--bureau-de-la-grave" },
  { path: "/#/bakery/boulangerie-leyes" },
  { path: "/#/bakery/chteau-de-la-btie-durf" },
  { path: "/#/bakery/une-histoire-de-got" },
  { path: "/#/bakery/la-boulangerie-cdric-hombecq" },
  { path: "/#/bakery/aux-sources-du-pain" },
  { path: "/#/bakery/la-vronnaise" },
  { path: "/#/bakery/le-mange-des-pains" },
  { path: "/#/bakery/boulangerie-le-vieux-four" },
  { path: "/#/bakery/boulangerie-patisserie" },
  { path: "/#/bakery/auberge-de-villar-darne" },
  { path: "/#/bakery/boulangerie-florence-poirier" },
  { path: "/#/bakery/le-boulanger-de-saint-louis" },
  { path: "/#/bakery/faades-varoises" },
  { path: "/#/bakery/le-fournil-du-perget-ii" },
  { path: "/#/bakery/boulanger-toulouse--colomiers" },
  { path: "/#/bakery/aux-pains-de-castagniers" },
  { path: "/#/bakery/denis-petesic-saveurs-retrouves" },
  { path: "/#/bakery/ptisserie-palanque-et-fils-sarl" },
  { path: "/#/bakery/boulangerie-du-peyra" },
  { path: "/#/bakery/la-boulangerie-des-laitires" },
  { path: "/#/bakery/boulangerie-grasse-dlices" },
  { path: "/#/bakery/boulangerie-grasset" },
  { path: "/#/bakery/boulangerie-grasset-march-vendredi" },
  { path: "/#/bakery/boulangerie-grasset-bio-et-artisanale" },
  { path: "/#/bakery/boulangerie-grasset-sur-le-march-le-mercredi" },
  { path: "/#/bakery/boulangerie-gourmande-de-saint-lger" },
  { path: "/#/bakery/golf-du-chteau-de-la-chouette" },
  { path: "/#/bakery/bohme-christophe" },
  { path: "/#/bakery/au-pain-dantan" },
  { path: "/#/bakery/la-fourne-de-pierre" },
  { path: "/#/bakery/le-fournil-de-peymeinade" },
  { path: "/#/bakery/librairie-caf-trait-dunion" },
  { path: "/#/bakery/les-dlices-dalexis" },
  { path: "/#/bakery/le-ptit-chef" },
  { path: "/#/bakery/boulangerie-stphanie-et-jean-pierre" },
  { path: "/#/bakery/intermarch-super-roquefort-les-pins" },
  { path: "/#/bakery/dechetterie-de-roquefort-les-pins" },
  { path: "/#/bakery/les-garons-villefranche-sur-mer" },
  { path: "/#/bakery/boulangerie-du-golf" },
  { path: "/#/bakery/boulangerie-la-tourtelle" },
  { path: "/#/bakery/boulangerie-ptisserie" },
  { path: "/#/bakery/le-boulanger-de-la-tour" },
  { path: "/#/bakery/achills-restaurant-bar-rooftop-villefranche-sur-mer" },
  { path: "/#/bakery/boulangerie-ptisserie-latour" },
  { path: "/#/bakery/boulangerie-de-la-tourelle" },
  { path: "/#/bakery/latourrette-michael" },
  { path: "/#/bakery/garellis" },
  { path: "/#/bakery/la-boulange-de-bermond" },
  { path: "/#/bakery/saint-paul-de-vence" },
  { path: "/#/bakery/moulin-de-mjane" },
  { path: "/#/bakery/saint-paul-de-vence-cimetire" },
  { path: "/#/bakery/collge-saint-blaise--st-sauveur-sur-tine" },
  { path: "/#/bakery/les-boulangeries-des-gaves" },
  { path: "/#/bakery/boulangerie-ptisserie-f-de-saint-jores" },
  { path: "/#/bakery/boulange" },
  { path: "/#/bakery/laudace-des-saveurs-by-damien-audax" },
  { path: "/#/bakery/moindrot-dominique-henri-jacques" },
  { path: "/#/bakery/auribeau-sur-siagne-le-pr-fanton" },
  { path: "/#/bakery/ma-premiere-boulangerie" },
  { path: "/#/bakery/boulanger-brianon" },
  { path: "/#/bakery/la-boule-meije" },
  { path: "/#/bakery/boulangerie-lefebvre" },
  { path: "/#/bakery/boulangerie-castillon" },
  { path: "/#/bakery/boulangerie-ptisserie-aux-dlices-des-4-valles" },
  { path: "/#/bakery/les-douceurs-descragnolles" },
  { path: "/#/bakery/boulangerie-belvdre" },
  { path: "/#/bakery/le-belvedere" },
  { path: "/#/bakery/demont-boulangerie" },
  { path: "/#/bakery/boulangerie-latelier-de-pain-pain" },
  { path: "/#/bakery/boulangerie-beuilloise" },
  { path: "/#/bakery/collin-valentin" },
  { path: "/#/bakery/boulangerie-veziano" },
  { path: "/#/bakery/boulangerie-de-la-gare" },
  { path: "/#/bakery/boulangerie-ange-antibes" },
  { path: "/#/bakery/aux-saveurs-de-prat" },
  { path: "/#/bakery/au-bon-pain-moulissois" },
  { path: "/#/bakery/boulangerie-ptisserie--maison-lasserre" },
  { path: "/#/bakery/boulangerie-brier" },
  { path: "/#/bakery/boulangerie-briend" },
  { path: "/#/bakery/boulangerie-chocolatier-brie-nicolas" },
  { path: "/#/bakery/le-saint-honor" },
  { path: "/#/bakery/boulangerie-les-plaisirs-danala" },
  { path: "/#/bakery/boulangerie-patisserie-aux-plaisirs-gourmands" },
  { path: "/#/bakery/boulangerie-ptisserie--blengini-laurent" },
  { path: "/#/bakery/latelier-papilles-grasse" },
  { path: "/#/bakery/le-panificateur-matre-artisan-boulanger" },
  { path: "/#/bakery/boulangerie-cretu" },
  { path: "/#/bakery/valro-boulangerie-patisserie-st-roch" },
  { path: "/#/bakery/boulangerie-pujol" },
  { path: "/#/bakery/dorey-laurent" },
  { path: "/#/bakery/denis-gourdet-artisan-patissier" },
  { path: "/#/bakery/le-fournil-dantan" },
  { path: "/#/bakery/boulangerie-les-bls-banette-clermont-ferrand" },
  { path: "/#/bakery/boulangerie-clementel" },
  { path: "/#/bakery/boulangerie-soulas" },
  { path: "/#/bakery/boulangerie-ptisserie-patrice-soulabaille" },
  { path: "/#/bakery/lami-du-pain" },
  { path: "/#/bakery/boulangerie-du-viaduc-by-clment-soulavie-" },
  { path: "/#/bakery/boulangerie-comont-as" },
  { path: "/#/bakery/le-fournil-de-chaumont" },
  { path: "/#/bakery/au-fournil-chaumontais" },
  { path: "/#/bakery/connexion-partenaire-boulanger-exincourt" },
  { path: "/#/bakery/la-comtoise" },
  { path: "/#/bakery/boulangerie-patisserie-fontana" },
  { path: "/#/bakery/boulangerie-de-sospel" },
  { path: "/#/bakery/boulangerie-ptisserie-sospel-demaria" },
  { path: "/#/bakery/le-fournil-de-pont-scorff" },
  { path: "/#/bakery/huguet-christophe" },
  { path: "/#/bakery/le-kiosque-pizzas-troyes-saint-julien-les-villas" },
  { path: "/#/bakery/mairie-saint-julien-les-villas" },
  { path: "/#/bakery/ferme-de-la-diligence--saint-julien-les-villas" },
  { path: "/#/bakery/lepi-dothe" },
  { path: "/#/bakery/le-fournil-des-gres" },
  { path: "/#/bakery/hotel-le-croiseur" },
  { path: "/#/bakery/boulangerie-patisserie-le-fournil-de-jrme" },
  { path: "/#/bakery/au-fournil-de-bernon" },
  { path: "/#/bakery/maison-lorel" },
  { path: "/#/bakery/maison-montero" },
  { path: "/#/bakery/du-pain-sur-la-planche" },
  { path: "/#/bakery/boulangerie-ptisserie-artisanale-au-four-dampierrois" },
  { path: "/#/bakery/la-boulangerie-pesta" },
  { path: "/#/bakery/les-petits-gourmets" },
  { path: "/#/bakery/boulangerie-dg-sarl" },
  { path: "/#/bakery/la-ptite-patisserie" },
  { path: "/#/bakery/boulangerie-ptisserie-zola" },
  { path: "/#/bakery/bara--boulangerie-patisserie--nantes" },
  { path: "/#/bakery/mch" },
  { path: "/#/bakery/boulanger-dijon--quetigny" },
  { path: "/#/bakery/chteau-les-carmes-haut-brion" },
  { path: "/#/bakery/boulangerie-ptisserie-epi-clguerois" },
  { path: "/#/bakery/le-fournil-agrsien" },
  { path: "/#/bakery/boulangerie-bonotti" },
  { path: "/#/bakery/boulangerie-jollivet-dominique" },
  { path: "/#/bakery/du-moulin-au-pain" },
  { path: "/#/bakery/la-ptrie" },
  { path: "/#/bakery/boulanger-villiers-sur-marne" },
  { path: "/#/bakery/les-dlices-des-pains" },
  { path: "/#/bakery/la-passion-du-gout" },
  { path: "/#/bakery/boulangerie-buffard" },
  { path: "/#/bakery/le-delice-montbazinois" },
  { path: "/#/bakery/skatepark-la-chapelle-saint-luc" },
  { path: "/#/bakery/ford-troyes--groupe-amplitude" },
  { path: "/#/bakery/general-troc" },
  { path: "/#/bakery/la-belinenne-artisan-boulanger-banette" },
  { path: "/#/bakery/le-fournil-belineen" },
  { path: "/#/bakery/boulangerie-vandenberghe" },
  { path: "/#/bakery/boulangerie-durik" },
  { path: "/#/bakery/chateau-fort-de-roquetaillade" },
  { path: "/#/bakery/les-douceurs-du-chene" },
  { path: "/#/bakery/boulangerie-allouville-bellefosse-les-gourmandises-du-chne" },
  { path: "/#/bakery/boulangerie-gava" },
  { path: "/#/bakery/boulangerie-gauchey" },
  { path: "/#/bakery/le-fournil-daudenge" },
  { path: "/#/bakery/les-petites-gourmandises-dici" },
  { path: "/#/bakery/boulangerie-la-ptrie" },
  { path: "/#/bakery/celisa" },
  { path: "/#/bakery/boulangerie-ptisserie-la-trainelloise" },
  { path: "/#/bakery/boulangerie-ptisserie-pontoise" },
  { path: "/#/bakery/guine-jean-yves" },
  { path: "/#/bakery/la-baguette-des-granges" },
  { path: "/#/bakery/le-domaine-du-val-dauzon-service-vnementiel" },
  { path: "/#/bakery/golf-du-val-dauzon" },
  { path: "/#/bakery/garden-palace-cabaret" },
  { path: "/#/bakery/la-comtesse" },
  { path: "/#/bakery/comtesse-du-barry" },
  { path: "/#/bakery/htel-la-comtesse-tour-eiffel" },
  { path: "/#/bakery/mosella-buffet" },
  { path: "/#/bakery/marques-avenue-metz--talange" },
  { path: "/#/bakery/la-miche-au-levain" },
  { path: "/#/bakery/intermarch-super-creney-prs-troyes" },
  { path: "/#/bakery/meynard-jean-christophe" },
  { path: "/#/bakery/boulangerie-ptisserie-jacinto-daniel" },
  { path: "/#/bakery/commune-mussy-sur-seine" },
  { path: "/#/bakery/la-cit-des-pierres-mussy-sur-seine" },
  { path: "/#/bakery/gallas-yannick-andre" },
  { path: "/#/bakery/menuiserie-en-othe" },
  { path: "/#/bakery/boulangerie-o-bonheur-de-nos-gens" },
  { path: "/#/bakery/au-fournil-de-varennes" },
  { path: "/#/bakery/nevers-eurl" },
  { path: "/#/bakery/la-geneuilloise" },
  { path: "/#/bakery/boulangerie-ptisserie-saint-aubin" },
  { path: "/#/bakery/boulangerie-sonveau" },
  { path: "/#/bakery/au-bl-dor" },
  { path: "/#/bakery/boulanger-digne-les-bains" },
  { path: "/#/bakery/boulangerie-ptisserie-vial-bras-dasse" },
  { path: "/#/bakery/hareaut-frdric" },
  { path: "/#/bakery/boulangerie-barre" },
  { path: "/#/bakery/boulangerie-zurek" },
  { path: "/#/bakery/maison-viennet" },
  { path: "/#/bakery/boulanger-saint-nazaire--trignac" },
  { path: "/#/bakery/boulangerie-achatain" },
  { path: "/#/bakery/boulangerie-ptisserie-vinci" },
  { path: "/#/bakery/boulangerie-relais-des-granges" },
  { path: "/#/bakery/la-boulangerie-de-la-gare" }
]

module.exports = configure(function (ctx) {
  return {
    // https://v2.quasar.dev/quasar-cli-webpack/supporting-ts
    supportTS: false,

    // https://v2.quasar.dev/quasar-cli-webpack/prefetch-feature
    // preFetch: true,

    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://v2.quasar.dev/quasar-cli-webpack/boot-files
    boot: [
      'i18n'
    ],

    // https://v2.quasar.dev/quasar-cli-webpack/quasar-config-js#Property%3A-css
    css: [
      'bootstrap.min.scss',
      'app.scss',
      'material.scss'
    ],

    // https://github.com/quasarframework/quasar/tree/dev/extras
    extras: [
      // 'ionicons-v4',
      // 'mdi-v5',
      // 'fontawesome-v6',
      // 'eva-icons',
      // 'themify',
      // 'line-awesome',
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      // 'roboto-font', // optional, you are not bound to it
      // 'material-icons' // optional, you are not bound to it
    ],

    // Full list of options: https://v2.quasar.dev/quasar-cli-webpack/quasar-config-js#Property%3A-build
    build: {
      vueRouterMode: 'hash', // available values: 'hash', 'history'

      env: envparser(),
      publicPath: ctx.prod ? process.env.WEBSITE_LOCAL : '',

      extendWebpack(cfg) {
        cfg.plugins.push(
          new SitemapPlugin({
            base: 'https://my-bakery.fr',
            paths,
            options: {
              filename: 'sitemap.xml',
              lastmod: true,
              changefreq: 'weekly',
            }
          })
        ),
          cfg.plugins.push(
            new CopyWebpackPlugin([{ context: `${__dirname}/src/assets`, from: `*.*` }])
          )
      },

      // transpile: false,

      // Add dependencies for transpiling with Babel (Array of string/regex)
      // (from node_modules, which are by default not transpiled).
      // Applies only if "transpile" is set to true.
      // transpileDependencies: [],

      // rtl: true, // https://quasar.dev/options/rtl-support
      // preloadChunks: true,
      // showProgress: false,
      // gzip: true,
      // analyze: true,

      // Options below are automatically set depending on the env, set them if you want to override
      // extractCSS: false,

      // https://v2.quasar.dev/quasar-cli-webpack/handling-webpack
      // "chain" is a webpack-chain object https://github.com/neutrinojs/webpack-chain

    },

    // Full list of options: https://v2.quasar.dev/quasar-cli-webpack/quasar-config-js#Property%3A-devServer
    devServer: {
      server: {
        type: 'http'
      },
      allowedHosts: ['my-bakery.fr', 'localhost'],
      port: 8080,
      headers: {
        'Access-Control-Allow-Methods': 'GET, POST',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
        'Access-Control-Allow-Origin': '*',
      },
      open: true // opens browser window automatically
    },

    // https://v2.quasar.dev/quasar-cli-webpack/quasar-config-js#Property%3A-framework
    framework: {
      config: {},

      // iconSet: 'material-icons', // Quasar icon set
      // lang: 'fr-FR', // Quasar language pack

      // For special cases outside of where the auto-import strategy can have an impact
      // (like functional components as one of the examples),
      // you can manually specify Quasar components/directives to be available everywhere:
      //
      // components: [],

      // Quasar plugins
      plugins: [
        'Cookies',
        'Meta',
        'Notify',
        'Loading'
      ]
    },

    // animations: 'all', // --- includes all animations
    // https://quasar.dev/options/animations
    animations: 'all',

    // https://v2.quasar.dev/quasar-cli-webpack/developing-ssr/configuring-ssr
    ssr: {
      pwa: false,

      // manualStoreHydration: true,
      // manualPostHydrationTrigger: true,

      prodPort: 3000, // The default port that the production server should use
      // (gets superseded if process.env.PORT is specified at runtime)

      maxAge: 1000 * 60 * 60 * 24 * 30,
      // Tell browser when a file from the server should expire from cache (in ms)

      middlewares: [
        ctx.prod ? 'compression' : '',
        'render' // keep this as last one
      ]
    },

    // https://v2.quasar.dev/quasar-cli-webpack/developing-pwa/configuring-pwa
    pwa: {
      workboxPluginMode: 'GenerateSW', // 'GenerateSW' or 'InjectManifest'
      workboxOptions: {}, // only for GenerateSW

      // for the custom service worker ONLY (/src-pwa/custom-service-worker.[js|ts])
      // if using workbox in InjectManifest mode

      manifest: {
        name: 'My bakery - classement des meilleurs boulangerie de France',
        short_name: 'My bakery - classement des meilleurs boulangerie de France',
        description: 'Retrouvez toutes les meilleures boulangeries en France sur My bakery.',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#ffffff',
        icons: [
          {
            src: 'icons/icon-128x128.png',
            sizes: '128x128',
            type: 'image/png'
          },
          {
            src: 'icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: 'icons/icon-256x256.png',
            sizes: '256x256',
            type: 'image/png'
          },
          {
            src: 'icons/icon-384x384.png',
            sizes: '384x384',
            type: 'image/png'
          },
          {
            src: 'icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      }
    },

    // Full list of options: https://v2.quasar.dev/quasar-cli-webpack/developing-cordova-apps/configuring-cordova
    cordova: {
      // noIosLegacyBuildFlag: true, // uncomment only if you know what you are doing
    },

    // Full list of options: https://v2.quasar.dev/quasar-cli-webpack/developing-capacitor-apps/configuring-capacitor
    capacitor: {
      hideSplashscreen: true
    },

    // Full list of options: https://v2.quasar.dev/quasar-cli-webpack/developing-electron-apps/configuring-electron
    electron: {
      bundler: 'packager', // 'packager' or 'builder'

      packager: {
        // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options

        // OS X / Mac App Store
        // appBundleId: '',
        // appCategoryType: '',
        // osxSign: '',
        // protocol: 'myapp://path',

        // Windows only
        // win32metadata: { ... }
      },

      builder: {
        // https://www.electron.build/configuration/configuration

        appId: 'my-bakery'
      }

      // "chain" is a webpack-chain object https://github.com/neutrinojs/webpack-chain

    }
  }
})
